Silly Player Names Rewrite
Valansch/RedMew pull request #1018
Opened 2019-12-25 06:31 UTC by theorangeangle

2019-12-25 16:46 UTC, Zahir-Khan commented
Done have permissions to edit...
line 53: local function create_name(words_table)
line 66: local function create_unique_name(words_table)
line 68: local name = create_name(words_table)
line 71: name = create_name(words_table)
line 96: local name = create_unique_name(naming_words)
line 130: local player = game.get_player(event.player_index)

2019-12-25 16:47 UTC, Zahir-Khan commented
line 59: return name

2020-01-07 03:29 UTC, mheguy requested changes
Silly player names had a fatal flaw, and I have no idea if changes to factorio have resolved that issue. When players connect to a server, the server checks if the connecting client's `name` matches a current LuaPlayer's name in game.players. If there is no corresponding name, a new LuaPlayer is created for the connecting client.
So let's say we have `orange` who connects and has their name changed to `not_orange`. The server "is shut down for maintenance" (read: crashes) while `orange` is online. When the server comes back online and `orange` reconnects, the server does not have a `LuaPlayer` named `orange`, therefore a new LuaPlayer will be connected and `orange` will not have any of the inventory that `not_orange` has. Further, they will not receive the name `not_orange` again unless by random chance.

So assuming Wube hasn't changed how players are identified to servers: this module should come with a significant warning to let people know that it is not stable.

2020-01-07 03:29 UTC, plague006 commented on map_gen/shared/silly_player_names.lua
> +global.silly_regulars = {}
This doesn't do anything. I wrote this over a year ago for a very different user_group system.

2020-01-07 03:29 UTC, plague006 commented on map_gen/shared/silly_player_names.lua
> +local function check_regular(real_name, silly_name, old_silly_name)
This entire function does nothing with the current user system.

2020-01-07 03:29 UTC, plague006 commented on map_gen/shared/silly_player_names.lua
> +-- @param player_name string with player's name
Outdated doc

2020-01-07 03:29 UTC, plague006 commented on map_gen/shared/silly_player_names.lua
> +-- @param player_name string with player's name
Outdated doc

2020-01-07 03:29 UTC, plague006 commented on map_gen/shared/silly_player_names.lua
> +    -- After they have their name, we need to ensure compatibility with the regulars system
Outdated as the regulars/permission system has changed.

2020-02-18 18:54 UTC, SimonFlapse requested changes

2020-02-18 18:54 UTC, SimonFlapse commented on map_gen/shared/silly_player_names.lua
> +    player.name = name
From Factorio version 0.18.7 we are no longer able to change a players name. https://lua-api.factorio.com/latest/LuaPlayer.html#LuaPlayer.name

An alternative would be to render (Using the luaRendering) the silly names above the players head. How to handle the chat messages I don't know at the moment.

2020-02-18 18:54 UTC, SimonFlapse commented on map_gen/shared/silly_player_names.lua
> +        player.name = data_silly_names.silly_name_store[event.player_index]
API no longer available, see previous comment

2020-02-18 18:54 UTC, SimonFlapse commented on map_gen/shared/silly_player_names.lua
> +    player.name = data_silly_names.actual_name[player.index]
API no longer available, see previous comment

2020-05-10 22:25 UTC, theorangeangle commented
Seeing as how we can no longer change names, i'm going to move this one to the graveyard - it's going to take more effort than it's worth at this point to bring back into a usable state.

2020-05-10 22:25 UTC, closed without merging