Ping corpse location on player death
Valansch/RedMew pull request #1105
Opened 2020-11-08 13:15 UTC by grilledham

2020-11-08 15:40 UTC, Jayefuu commented
This is a great addition! Being able to look up in the chat to find  a marker to a body will be really useful.

Do you think it might be better to use player.print instead of player.force.print? The ping noise every time someone dies could be annoying and it will be easier to find your corpse ping if it messages only one player not all players upon death so there aren't lots of other pings to choose from.

2020-11-14 07:21 UTC, Jayefuu requested changes
Looks good. Just a minor change needed and a question.

2020-11-14 07:21 UTC, Jayefuu commented on features/server.lua
`message[#message + 1] = ' was killed by '` should be `message[#message + 1] = ' was killed by a'` so that the message is "grilledham was killed by a train" or "grilledham was killed by a fish".

2020-11-14 07:21 UTC, Jayefuu commented on features/server.lua
> +end)
Is  there a good reason to build the message as an array then concatenate it rather than doing:
`print(player.name .. "was killed by a " .. cause.name .. ". [gps='" .. string.format('%.1f', position.x) .. "," .. string.format('%.1f', position.y) .. "," .. player.surface.name .. "]")` ?

2020-11-14 11:55 UTC, grilledham commented on features/server.lua
I don't disagree with you that the grammar is wrong, but it's consistent with the death messages that factorio outputs i.e. factorio does this `"grilledham was killed by Fish"`. 
We would also have to handle the case of being killed by a player differently i.e. `"grilledham was killed by a Jayefuu"` wouldn't be right.
Do you think it's worth making the change?

2020-11-14 11:59 UTC, grilledham commented on features/server.lua
> +end)
That wouldn't handle the case of `cause` being nil`.

But I assume your question is about `table.concat` vs the concat operator `..`. `..` is inefficient because it allocates a new string for each concat, whereas the `table.concat` function can be more efficient in how it contacts strings. I’m not sure what the actual implementation is. So when doing multiple concats I’ve gotten into the habit of using `table.concat`.

2020-11-14 21:45 UTC, grilledham commented on features/server.lua
I've added an 'a' when not killed by a player.

2020-11-15 08:13 UTC, Jayefuu requested changes

2020-11-15 08:13 UTC, Jayefuu commented on features/server.lua
I've just retested this. I have two issues that I'm not sure are new or just un-noticed previously:
1) The cause printed to discord is event.cause.name which prints:
` Jayefuu was killed by a medium-worm-turret. [gps=0.0,0.0,redmew]`
event.cause.name needs changing to a human readable name instead, event.cause.localised_name.
2) However the in-game message is still `Jayefuu was killed by Medium worm`. Do we have control over this death message? If so this should also be changed to add "a" if it's not a player that killed the player.

2020-11-15 10:59 UTC, grilledham commented on features/server.lua
1. We can't print localised names to discord, I think we just have to live with that.
2. We can't control the default message that Factorio prints in game.

2020-11-15 11:17 UTC, Jayefuu approved these changes

2020-11-15 11:24 UTC, merged