Fixed part of artillery pickup exploit
Valansch/RedMew pull request #1116
Opened 2020-11-29 21:29 UTC by Jayefuu

- Current behaviour is that when destroyers/defenders are created their target position is set to the entity that killed them.
- If a player picks up the artillery after the capsules spawn then they lose their cause.target and stop, not reaching the cause of the turret death. If the player picks up the artillery after it spawns the killing projectile but before it hits the target, then the event has no cause and no bots spawn!
- I've changed this behaviour so that if the target.cause is artillery then it spawns a defender/destroyer projectile NOT an entity. The projectile target can therefore be a position not an entity. So the capsules won't stop if the artillery is picked up.
- If the cause is not artillery turret or wagon then a destroyer/defender capsule entity is spawned instead of a projectile because a projectile cannot track the player. This will mean we'll still get the nice behaviour where the capsule target updates as the player/tank/car/spidertron moves and they can kite them.
- If the player picks up the artillery turret before the projectile that kills a turret arrives then the event cause.name will be missing and no bots spawn at all. I have changed the behaviour so that "if not cause" then we assume they're doing something fucky. We won't have the entity cause name or position, so let's just spawn double the normal amount of destroyers and just send them at 0, 0 since we know nothing else to do with them.

2020-11-29 21:38 UTC, grilledham commented on map_gen/maps/crash_site/events.lua
> -    if not bot_spawn_whitelist[entity_name] then
Why is this check no longer at the top? Does this mean if you kill enemy walls with artillery and remove the artillery before the wall dies that lots of enemy bots are sent to spawn?

2020-11-29 21:53 UTC, Jayefuu commented on map_gen/maps/crash_site/events.lua
> -    if not bot_spawn_whitelist[entity_name] then
Woops! Thanks. I've fixed it so that it returns if not whitelist and not nil cause.

2020-11-30 17:09 UTC, grilledham requested changes

2020-11-30 17:09 UTC, grilledham commented on map_gen/maps/crash_site/events.lua
> +    end
This still isn't correct. In the case that the entity is not on the whitelist, e.g. walls and the artillery turret has been removed, this would still spawn bots.

Also I think the check should be at the `if not bot_spawn_whitelist[entity_name]` should be at the very top of the function, so we don't do any unnecessarily work if we can avoid it.

2020-12-13 15:04 UTC, grilledham commented on map_gen/maps/crash_site/events.lua
> +        if (entity_name == 'artillery-turret') or (entity_name == 'artillery-wagon') then
No action required here unless you want to change it, but why are we checking for 'artillery-wagon' there are no enemy artillery-wagons on crashsite?

2020-12-13 15:52 UTC, Jayefuu commented on map_gen/maps/crash_site/events.lua
> +        if (entity_name == 'artillery-turret') or (entity_name == 'artillery-wagon') then
I got confused between entity_name and cause.name I think. Will update.

2020-12-13 15:59 UTC, grilledham approved these changes

2020-12-13 16:06 UTC, merged