Added white text above player when mentioned in chat
Valansch/RedMew pull request #1153
Opened 2021-01-19 13:38 UTC by Jayefuu

The notification sound for text chat mentions isn't useful if player is deaf or has sound off.

Recently we've had lots of players not reading the chat when they're being spoken to and often results in jailing or popups while we get their attention.

This commit adds white text above their player character (visible only to them) that disappears after 3 seconds.

2021-01-19 13:40 UTC, Jayefuu commented
![image](https://user-images.githubusercontent.com/28716932/105042194-d959d900-5a5b-11eb-8d55-e6b33520c52b.png)

2021-01-19 13:52 UTC, SimonFlapse approved these changes
LGTM

2021-01-19 13:52 UTC, SimonFlapse commented on features/chat_triggers.lua
> +                    local message = game.get_player(event.player_index).name .. ' mentioned you in the chat!'
Could you by any chance transfer this string to the locales for translation?

Same with line 104

2021-01-19 13:52 UTC, SimonFlapse commented on features/chat_triggers.lua
>                      p.print(prefix .. game.get_player(event.player_index).name .. ' mentioned you!', Color.yellow)
Could you by any chance transfer this string to the locales for translation?

Same with line 106

2021-01-19 15:30 UTC, Jayefuu commented on features/chat_triggers.lua
>                      p.print(prefix .. game.get_player(event.player_index).name .. ' mentioned you!', Color.yellow)
Yup no problem. Will do.

2021-01-19 20:25 UTC, grilledham requested changes
Cool feature.

Some thoughts:
- For small messages (< 250 characters?) it might be better to print the message itself, rather than a message that you have a message.
- Use the chat color of the sending player.

2021-01-19 20:25 UTC, grilledham commented on features/chat_triggers.lua
> +                    local message = game.get_player(event.player_index).name .. ' mentioned you in the chat!'
```suggestion
                    local message = player.name .. ' mentioned you in the chat!'
```
And the same for line 104 above.

2021-01-19 20:25 UTC, grilledham commented on features/chat_triggers.lua
> +                    rendering.draw_text({text =  message, target_offset  = {0,-3},surface = p.surface, target = p.character, time_to_live = 180, alignment="center", scale=2, players={p.name}, color=
What happens if `p.character` is `nil`?

2021-01-20 09:16 UTC, Jayefuu commented
@grilledham 
- I'm against using the colour of the sending player. White is universally visible whereas some players choose hard to read colours. If I'm adding this as an accessibility feature I'd prefer it to always be the same colour.
- re. short messages less than 250 characters appearing directly over the character, I'm not sure. I could code it up to try it but I think it will be confusing. Also if someone isn't replying and we ping them, we might just use their name to get their attention so we don't have to repeat several lines of conversation. For example asking a player not to do something, we tell them why and discuss among ourselves, then someone pings their name to get them to read the chat. This nicely tells them their attention is required.
- I'll fix the p.character issue and player.name stuff this evening :)

2021-01-20 09:17 UTC, Jayefuu commented on features/chat_triggers.lua
> +                    local message = game.get_player(event.player_index).name .. ' mentioned you in the chat!'
Done.

2021-01-20 09:17 UTC, Jayefuu commented on features/chat_triggers.lua
>                      p.print(prefix .. game.get_player(event.player_index).name .. ' mentioned you!', Color.yellow)
Done.

2021-01-21 14:54 UTC, Jayefuu commented on features/chat_triggers.lua
> +                    rendering.draw_text({text =  message, target_offset  = {0,-3},surface = p.surface, target = p.character, time_to_live = 180, alignment="center", scale=2, players={p.name}, color=
I've added a check for this now. The player won't get white text when they're dead, but it would have errored before. I think this is okay since if they're dead they'll probably be bored and looking at the chat.

2021-01-21 14:54 UTC, Jayefuu commented
@grilledham I think that's everything....

2021-01-21 17:18 UTC, grilledham approved these changes
Looks good. You seems to left in the old code commented out. After you remove that you can merge.

2021-01-21 17:18 UTC, grilledham commented on features/chat_triggers.lua
> +                    --p.print({'chat_triggers.mention_success_target', prefix, game.get_player(event.player_index).name}, Color.yellow)
Can you remove this commented out code.

2021-01-21 17:18 UTC, grilledham commented on features/chat_triggers.lua
> +                        --local message = {'chat_triggers.mention_success_target_floating', game.get_player(event.player_index).name}
Can you remove this commented out code here too.

2021-01-23 17:41 UTC, merged