Sandworms: Fixed callback crash when no position for worm found
Valansch/RedMew pull request #1161
Opened 2021-01-26 16:29 UTC by Jayefuu

- If it couldn't find a non-colliding position it errored when trying to use the worm position to spawn biters
- This would cause the callback to stop working and the roboport wouldn't spawn worms.
- Fixed by adding check for nil worm position

2021-01-26 16:51 UTC, grilledham requested changes

2021-01-26 16:51 UTC, grilledham commented on map_gen/maps/crash_site/features/sandworms.lua
> +            s.create_entity {name = index, position = worm_position, force = "enemy"}
I would suggest using a different variable name for the returned worm_position to avoid confusion with the random target location.
```lua
local free_worm_position = s.find_non_colliding_position(index, worm_position, 20, 1)
if not free_worm_position then
	return
end
s.create_entity {name = index, position = free_worm_position, force = "enemy"}
```
That way when spawning multiple worms they are all spawn within a range around the target location rather than from the previous spawned worm. Which currently means the maximum range a worm could theoretically spawn from a roboport is 20 * 4 + max_worm_spawn_radius, which I assume is unintended.

2021-01-28 09:19 UTC, Jayefuu commented on map_gen/maps/crash_site/features/sandworms.lua
> +            s.create_entity {name = index, position = worm_position, force = "enemy"}
You're right, thank you. I've updated this.

2021-01-28 21:01 UTC, grilledham approved these changes

2021-01-28 22:23 UTC, merged