Added configurable pollution to outposts for future testing
Valansch/RedMew pull request #1167
Opened 2021-02-02 18:27 UTC by Jayefuu

My plan is to make a harder crash site version where getting free resources from outposts creates pollution.

My intention is to balance it so it's still better to get items from outposts, but this commit is intended to give me a way to take saved games and test different amounts of pollution to check for balance. I don't intend to test this on live for a while but want to test it offline, this will give me the ability to turn it on half way through a game.

Need to consider how it doesn't take into account what the item is so it will be better to get free end-game items and probably limit how much iron we let into base later in the game. Might also create interesting meta where we are careful about what resources we take from outposts depending upon the pollution making setting.

2021-02-02 20:04 UTC, grilledham requested changes
Long term it would be good to move the commands out of the outpost_builders.lua, but as this is temporary I'll allow it for now.
The only thing that is really blocking this is that it's not desync safe. Let me know if you need any help with that.

2021-02-02 20:04 UTC, grilledham commented on map_gen/maps/crash_site/outpost_builder.lua
> +                if entity.get_output_inventory().can_insert(data.item) then -- No pollution once full. Taking items out of crafters makes pollution
make a local for inventory, so we don't have to call `get_output_inventory()` twice.

2021-02-02 20:04 UTC, grilledham commented on map_gen/maps/crash_site/outpost_builder.lua
> +    end
Are you planning on having multiple multipliers?
Can this just be
```suggestion
    local multiplier = tonumber(args.multiplier)
    if not multiplier then
        player.print("Fail")
        return
    end   
```

2021-02-02 20:04 UTC, grilledham commented on map_gen/maps/crash_site/outpost_builder.lua
> +    game.print(args.multiplier)
There are some places in this function where you use `game.print` they should probably be `player.print`.

2021-02-02 20:04 UTC, grilledham commented on map_gen/maps/crash_site/outpost_builder.lua
> +    pollution_multiplier = multipliers[1]
Setting `pollution_multiplier` like this isn't desync safe. When you set `pollution_multiplier` you are not changing the value stored in global. What you need to do is box the value in a table, i.e. `local pollution_multiplier = {0}`. Then read/write the value through the table.

2021-02-02 20:04 UTC, grilledham commented on map_gen/maps/crash_site/outpost_builder.lua
> +            p.print(player.name..' changed magic crafter pollution multiplier from '..old_multiplier..' to '..pollution_multiplier)
We know there is always going to be one admin, the admin who ran the command, so we could do the string concatenation once outside of the loop. This is just me being picky 😄.

2021-02-02 20:04 UTC, grilledham commented on map_gen/maps/crash_site/outpost_builder.lua
> +        allowed_by_server = false
Not allowed by server is odd, but I see that would make the `get_pollution_multiplier` function slightly more complicated.

2021-02-02 20:06 UTC, grilledham commented
Thinking about the future, I wonder if we want configurable pollution values per outpost type, or per recipe.
Also maybe the magic crafter should spawn with a full inventory, so there is no initial pollution.

2021-02-03 08:26 UTC, Jayefuu commented
> 
> 
> Thinking about the future, I wonder if we want configurable pollution values per outpost type, or per recipe.

I think that would be great. And much better for balancing. I'm not sure how to do it though.

> Also maybe the magic crafter should spawn with a full inventory, so there is no initial pollution.

That's so obvious. I should have caught that, I shall make it so.

2021-02-03 08:26 UTC, Jayefuu commented on map_gen/maps/crash_site/outpost_builder.lua
> +        allowed_by_server = false
I was being lazy. I'll look up how to resolve if it's from the server from another example somewhere.

2021-02-03 08:27 UTC, Jayefuu commented on map_gen/maps/crash_site/outpost_builder.lua
> +            p.print(player.name..' changed magic crafter pollution multiplier from '..old_multiplier..' to '..pollution_multiplier)
Nah, I appreciate it, need to get into better habits and this helps with that.

2021-02-03 08:58 UTC, Jayefuu commented on map_gen/maps/crash_site/outpost_builder.lua
> +    pollution_multiplier = multipliers[1]
I'm not sure I understand. In other places you directly write to the global vars. Such as outpost_count. I've had a go but I don't think I've done this right in the next commit.

2021-02-03 10:59 UTC, Jayefuu commented
@grilledham that was quite a messy last commit I made.
- I still haven't fixed the global desync issue I suspect and will need some help
- In taking a look at the magic crafters I've made them all start with full inventory so they shouldn't release pollution.
- I'm not sure how, but oil refineries now flash that they don't have power and I can't work out why

2021-02-03 19:47 UTC, grilledham commented on map_gen/maps/crash_site/outpost_builder.lua
> +    pollution_multiplier = multipliers[1]
`outpost_count` isn't a global var.

2021-02-03 20:33 UTC, grilledham reviewed
Haven't had time to play test this yet.

Thanks for renaming all the furnace typos 😄.

Not sure why oil refineries would now start flashing missing power, if you don't figure it out, I'll investigate later.

I think pollution_multiplier should be desync safe now.

2021-02-03 20:33 UTC, grilledham commented on map_gen/maps/crash_site/outpost_builder.lua
> +    local message = {player.name, ' changed magic crafter pollution multiplier from ', old_multiplier, ' to ', pollution_multiplier}
Are you missing a `table.concat`? You can't print a table unless it is a valid LocalisedString.

2021-02-03 20:33 UTC, grilledham commented on map_gen/maps/crash_site/outpost_builder.lua
> +            output_inv.insert {name = callback_data.output.item, count = 200}
If you just want a full stack you can just pass in a string.
```suggestion
            output_inv.insert(callback_data.output.item)
```

2021-02-03 20:33 UTC, grilledham commented on map_gen/maps/crash_site/outpost_builder.lua
> +        local has_fluid_output = callback_data.keep_active
Maybe we should rename `keep_active` to `has_fluid_output`

2021-02-03 20:33 UTC, grilledham commented on map_gen/maps/crash_site/outpost_builder.lua
> +        if recipe and not has_fluid_output then -- to avoid trying to put an item into a fluid inventory
I think this whole if, elseif, else block can be simplified to:
```lua
local recipe = callback_data.recipe
if recipe then
	entity.set_recipe(recipe)
	if not callback_data.keep_active then -- to avoid trying to put an item into a fluid inventory
		entity.get_output_inventory().insert(callback_data.output.item)
	end
else
	local furnace_item = callback_data.furnace_item
	if furnace_item then
		local inv = entity.get_inventory(2) -- defines.inventory.furnace_source
		inv.insert(furnace_item)                
		entity.get_output_inventory().insert(callback_data.output.item)
	end
end
```

2021-02-03 20:33 UTC, grilledham commented on map_gen/maps/crash_site/outpost_builder.lua
> +    player.print('Current pollution multiplier is: '..pollution_multiplier)
```suggestion
    player.print('Current pollution multiplier is: ' .. pollution_multiplier.value)
```

2021-02-05 15:25 UTC, Jayefuu commented
@grilledham I made the suggested changes but now I get an error in my logs and this outpost fails to build properly. I didn't manage to fix it, any ideas?

 `131.012 Script @C:/Users/James/AppData/Roaming/Factorio/temp/currently-playing/utils/task.lua:77: 'stack': table expected, got nil`

![image](https://user-images.githubusercontent.com/28716932/107053087-55774f00-67c6-11eb-80e6-39245233c1ae.png)

2021-02-05 21:24 UTC, grilledham commented on map_gen/maps/crash_site/outpost_builder.lua
> +            if not callback_data.keep_active then -- to avoid trying to put an item into a fluid inventory
You missed this when changing the table field name.
```suggestion
            if not callback_data.has_fluid_output then -- to avoid trying to put an item into a fluid inventory
```

2021-02-07 16:31 UTC, grilledham commented
> I'm not sure how, but oil refineries now flash that they don't have power and I can't work out why

They are flashing in the develop branch without your changes. I can't remember if they always flashed, but it doesn't seem related to your changes.

2021-02-07 16:44 UTC, grilledham commented on map_gen/maps/crash_site/outpost_builder.lua
> +    'set_pollution_multiplier',
Minor but we normally use dash '-' rather than underscore '_' for commands.

2021-02-07 16:44 UTC, grilledham commented on map_gen/maps/crash_site/outpost_builder.lua
> +local function get_pollution_multiplier(player)
This doesn't work. I think it should be.
```suggestion
local function get_pollution_multiplier(args, player)
```

2021-02-07 16:44 UTC, grilledham commented on map_gen/maps/crash_site/outpost_builder.lua
> +    local message = player.name..' changed magic crafter pollution multiplier from '..old_multiplier..' to '..pollution_multiplier
```suggestion
    local message = player.name..' changed magic crafter pollution multiplier from '..old_multiplier..' to '..pollution_multiplier.value
```

2021-02-07 16:44 UTC, grilledham commented on map_gen/maps/crash_site/outpost_builder.lua
> +                entity.get_output_inventory().insert(callback_data.output.item)
Thinking about it don't we also need to handle the fluid output case by inserting the fluid items.

2021-02-08 12:53 UTC, Jayefuu commented on map_gen/maps/crash_site/outpost_builder.lua
> +    'set_pollution_multiplier',
Updated in next commit

2021-02-08 12:53 UTC, Jayefuu commented on map_gen/maps/crash_site/outpost_builder.lua
> +local function get_pollution_multiplier(player)
Updated in next commit

2021-02-08 12:55 UTC, Jayefuu commented on map_gen/maps/crash_site/outpost_builder.lua
> +    local message = player.name..' changed magic crafter pollution multiplier from '..old_multiplier..' to '..pollution_multiplier
Updated in next commit

2021-02-08 12:57 UTC, Jayefuu commented on map_gen/maps/crash_site/outpost_builder.lua
> +                entity.get_output_inventory().insert(callback_data.output.item)
I decided not to do this because a) I'm lazy and b) I thought it would be fun to see if they worked out that fluids don't produce pollution. I can't remember the last time I saw someone connect up oil or petroleum on crash site. I was hoping it might bring back flamethrower meta if using oil produced less pollution than getting ammo from magic crafters.

Mostly a) but now I've defended it I quite like b) :D

2021-02-08 13:00 UTC, Jayefuu commented
I think that's everything @grilledham

2021-02-08 22:23 UTC, grilledham commented on map_gen/maps/crash_site/outpost_builder.lua
> +                entity.get_output_inventory().insert(callback_data.output.item)
I'm ok with the laziness 😄.

2021-02-08 22:24 UTC, grilledham approved these changes

2021-02-08 22:47 UTC, merged