Updated artillery behaviour to get rid of destroyer-capsule
Valansch/RedMew pull request #1180
Opened 2021-02-18 14:18 UTC by Jayefuu

Use of the destroyer-capsule projectile instead of destroyer capsule meant that the destroyers and defenders didn't attack player entities until they reached the destination. They also couldn't be shot down by a well defended wall, they'd fly over.

I changed to destroyer-capsule so that they couldn't pick the artillery up after the bots spawned as this would remove their target and cause them to float around.

By request I have reveret to the destroyers that can be shot down as they're more fun and at current balance the destroyers kill the artillery every time, which is not much fun when they cannot be defended against.

To mitigate against players picking up the artillery after the destroyer/defender spawns, artillery targets will become unminable for 5 seconds after the destroyer/defender deploys.

This leaves the bug where they can pick up the artillery before the last shell destroys the turret. I considered adding artillery to a table when placed and checking their ammo inventory once every few seconds. I was going to set all artillery turrets to unminable unless they have no ammo for 3 seconds, but this seems like a lot of work for a small bug.

2021-02-18 19:32 UTC, grilledham approved these changes

2021-02-18 19:32 UTC, grilledham commented on map_gen/maps/crash_site/events.lua
> +    function(data)
`data` could just be the entity itself, don't have to put it in a table.

2021-02-19 14:18 UTC, Jayefuu commented on map_gen/maps/crash_site/events.lua
> +    function(data)
I've now updated this.

2021-02-19 14:54 UTC, Jayefuu commented
Woops. I committed some changes to this branch I didn't mean to. Those need checking too @grilledham as I don't know how to uncommit them.

2021-02-19 15:07 UTC, grilledham requested changes

2021-02-19 15:07 UTC, grilledham commented on map_gen/maps/crash_site/outpost_builder.lua
> +    player = player or server_player
This is too low, it would need to happen before `player.print` 4 lines up.

2021-02-19 15:07 UTC, grilledham commented on map_gen/maps/crash_site/outpost_builder.lua
> +        required_rank = Ranks.regular,
What is the value of restricting this to regulars? If we let regulars do this we might as well let everyone.

2021-02-19 15:07 UTC, grilledham commented on map_gen/maps/crash_site/events.lua
> +        entity.minable = true
Now that I think about this again we need to check the entity is still valid, it might have killed.

2021-02-19 15:26 UTC, Jayefuu commented on map_gen/maps/crash_site/outpost_builder.lua
> +        required_rank = Ranks.regular,
None. I've switched it to guest.

2021-02-19 21:52 UTC, grilledham approved these changes

2021-02-20 08:15 UTC, merged