Updated the starting pollution multiplier
Valansch/RedMew pull request #1247
Opened 2021-09-27 21:09 UTC by Jayefuu

The new meta sucks. No one builds any walls or defences. Players can go 3 or 4 hours with no attacks so long as they craft nothing.

Now that the pollution from outposts is generated at position = {0,0}.... let's try a very small amount of pollution for every outpost captured to force at least a small amount of defences to be built.

This will be MUCH less pollution than if all of the items they get free were made in base, but it will still force at least a few defenses or clearing of nearby bases.

Starting with a value of 10 to see how it goes.

2021-09-27 21:15 UTC, grilledham commented on map_gen/maps/crash_site/outpost_builder.lua
> +        player.print("Cannot set the multiplier lower than the base multiplier of " .. base_pollution_multiplier)
Missing a `return`?
```suggestion
        pollution_multiplier.value = base_pollution_multiplier
        player.print("Cannot set the multiplier lower than the base multiplier of " .. base_pollution_multiplier)
        return
```

2021-09-27 22:17 UTC, Jayefuu commented on map_gen/maps/crash_site/outpost_builder.lua
> +        player.print("Cannot set the multiplier lower than the base multiplier of " .. base_pollution_multiplier)
Yis. Fixed.

2021-09-28 18:22 UTC, grilledham requested changes

2021-09-28 18:22 UTC, grilledham commented on map_gen/maps/crash_site/outpost_builder.lua
> +        pollution_multiplier.value = base_pollution_multiplier
```suggestion        
```
Looking at this again, I'm not sure what this line is for. What if `pollution_multiplier.value` was previously set to a valid value that is greater than `base_pollution_multiplier`. Do you want to silently change `pollution_multiplier.value` to a different value because someone try to set it to an invalid value?

Or am I missing something?

2021-09-29 16:07 UTC, grilledham approved these changes
Looks good.

One minor style point, you don't really need the `else` after the `return`.

2021-09-29 16:07 UTC, grilledham commented on map_gen/maps/crash_site/outpost_builder.lua
> +        end
```suggestion
        end
        -- update the value to the minimum and continue to message all admins
        player.print("Setting magic crafter pollution multiplier to the minimum value of " .. base_pollution_multiplier)
        multiplier = base_pollution_multiplier        
```

2021-09-30 10:25 UTC, merged