A point-and-click method to call AOE functions
Valansch/RedMew pull request #1295
Opened 2022-03-11 11:50 UTC by Jayefuu

Allows players to point and click to call strike and barrage instead of using text commands.

https://streamable.com/4e2ed6

- Create a new decon planner
- Change its icon to the desired method
- When decon planner is used, check they only clicked not dragged an area
- Check what the icon is and call the respective function  from commands.lua

Known issues:
- If you put the decon plannerin the game blueprints then take it out again it  doesn't work. I get this error: LuaItemStack API call when LuaItemStack was invalid for read. It's definitely a Lua item stack but it's invalid for some reason. This isn't an issue with the new code to work but I know players will want to store the decon planner in game blueprints.

2022-03-11 16:46 UTC, grilledham commented on map_gen/maps/crash_site/features/discharge_targetting_remote.lua
> +    local item_name = player.cursor_stack.name
`cursor_stack` can be `nil` I'd also add a valid check because why not.

2022-03-11 21:34 UTC, grilledham requested changes
We also discussed adding the deconstruction planners to the market. Feel free to add that as part of this PR or leave it for later.

2022-03-11 21:34 UTC, grilledham commented on map_gen/maps/crash_site/features/discharge_targetting_remote.lua
> +    if not player.cursor_stack.blueprint_icons[1].signal.name then
`blueprint_icons` could return an empty array. So we either need to check the size of the array or check the [1] doesn't return `nil`

I'd probably make a `local icon = player.cursor_stack.blueprint_icons[1]`

2022-03-11 21:34 UTC, grilledham commented on map_gen/maps/crash_site/features/discharge_targetting_remote.lua
> +    if (math.abs(event.area.left_top.x -  event.area.right_bottom.x) < 1) and (math.abs(event.area.left_top.y -  event.area.right_bottom.y) < 1)  then
I'd make locals for x and y.

2022-03-11 21:34 UTC, grilledham commented on map_gen/maps/crash_site/features/discharge_targetting_remote.lua
> +local Event = require 'utils.event'
Why is the file called "discharge_targetting_remote". I'm not sure what I'd call it but maybe just "targetting_remote"?

2022-03-11 21:34 UTC, grilledham commented on map_gen/maps/crash_site/commands.lua
> +    function Public.call_strike(args, player)
In cases like this you can just do:
```suggestion
    Public.call_strike = strike
```

2022-03-12 17:55 UTC, Jayefuu commented on map_gen/maps/crash_site/features/discharge_targetting_remote.lua
> +local Event = require 'utils.event'
I originally tried to use the capsule event to trigger stuff and was going to have a gui to switch between modes. I forgot to rename it.

2022-03-12 18:57 UTC, Jayefuu commented on map_gen/maps/crash_site/commands.lua
> +    function Public.call_strike(args, player)
Fixed

2022-03-12 18:57 UTC, Jayefuu commented on map_gen/maps/crash_site/features/discharge_targetting_remote.lua
> +    if (math.abs(event.area.left_top.x -  event.area.right_bottom.x) < 1) and (math.abs(event.area.left_top.y -  event.area.right_bottom.y) < 1)  then
Fixed

2022-03-12 18:58 UTC, Jayefuu commented
A few changes made but market for decon planners a work in progress.

2022-03-13 14:31 UTC, grilledham commented on map_gen/maps/crash_site/commands.lua
> +
Couldn't this instead be
```lua
local cursor_stack = player.cursor_stack
cursor_stack.set_stack({name = 'deconstruction-planner'})
cursor_stack.blueprint_icons = {{index = 1, signal = {type = 'item', name = 'poison-capsule'}}}
```

Also I guess we need to check that the cursor stack is empty first.

2022-03-13 15:07 UTC, Jayefuu commented
@grilledham I think I've now addressed all your comments.

2022-03-13 17:31 UTC, grilledham requested changes
I still need to give this a test.

Just a though, we might need to change the antigrief code (in nuke_control.lua) that removes deconstruction planners from guests, else they will have a bad time using this.

2022-03-13 17:31 UTC, grilledham commented on map_gen/maps/crash_site/features/deconstruction_targetting.lua
> +    if not player or not player.valid or not player.cursor_stack or not player.cursor_stack.valid then
LuaItemStacks are weird I think we also have to check [valid_for_read](https://lua-api.factorio.com/latest/LuaItemStack.html#LuaItemStack.valid_for_read)

I'd probably also make a local for cursor_stack.

2022-03-13 17:31 UTC, grilledham commented on map_gen/maps/crash_site/features/deconstruction_targetting.lua
> +    if not player.cursor_stack.blueprint_icons or not player.cursor_stack.blueprint_icons[1].signal.name then
`blueprint_icons[1]` could be `nil`

2022-03-13 17:31 UTC, grilledham commented on map_gen/maps/crash_site/scenario.lua
> +                price = 5,
Why is there a price for items players can make for free?

2022-03-13 18:30 UTC, Jayefuu commented on map_gen/maps/crash_site/scenario.lua
> +                price = 5,
I don't know. I thought it might prevent some spamming of them and people dropping them in chests. But since it goes to cursor now not into inventory that's less likely.

2022-03-14 22:15 UTC, merged