Added crash site /strike anti-grief
Valansch/RedMew pull request #1302
Opened 2022-03-17 10:21 UTC by Jayefuu

Wasn't necessary before. But with new point and click strike decon planners people are using them from their hot bar by mistake.

2022-03-17 20:21 UTC, grilledham requested changes

2022-03-17 20:21 UTC, grilledham commented on map_gen/maps/crash_site/commands.lua
> +            local enemies = s.find_entities_filtered{position = {xpos, ypos}, radius=radius+10, force="enemy"}
Use `count_entities_filtered` instead and `limit = 1`.

2022-03-17 20:21 UTC, grilledham commented on map_gen/maps/crash_site/commands.lua
> +                player.print("No enemies found at [gps="..xpos..","..ypos..","..s.name.."]. What a waste of poison capsules!",Color.fail)
Use localised string.

2022-03-17 22:53 UTC, Jayefuu commented on map_gen/maps/crash_site/commands.lua
> +            local enemies = s.find_entities_filtered{position = {xpos, ypos}, radius=radius+10, force="enemy"}
Thanks. Fixed

2022-03-17 22:54 UTC, Jayefuu commented on map_gen/maps/crash_site/commands.lua
> +                player.print("No enemies found at [gps="..xpos..","..ypos..","..s.name.."]. What a waste of poison capsules!",Color.fail)
Done

2022-03-18 15:48 UTC, grilledham approved these changes

2022-03-18 15:48 UTC, merged