Changes to spy reduce chat spam and improve usage visibility on map
Valansch/RedMew pull request #1303
Opened 2022-03-17 10:42 UTC by Jayefuu

- Added 30 second cooldown to spy chat message
- Still shows message on first use so that new players know about the command
- Added spy fish tag to map so that players can see easily which are the newly revealed areas.

2022-03-17 20:33 UTC, grilledham requested changes

2022-03-17 20:33 UTC, grilledham commented on map_gen/maps/crash_site/commands.lua
> +    local spy_message_cooldown = false
This is desync risk. In lua Booleans are value types so this is a copy of the value stored in global. The trick is to store the value inside a table which are reference types e.g.
```suggestion
    local spy_message_cooldown = {false}
```
And then the places where this is set would be `spy_message_cooldown[1] = true/false`

2022-03-17 22:44 UTC, Jayefuu commented on map_gen/maps/crash_site/commands.lua
> +    local spy_message_cooldown = false
Cool. Thanks

2022-03-18 15:50 UTC, grilledham approved these changes

2022-03-18 15:50 UTC, merged