A deconstruction planner control to easily group spiders to follow a …
Valansch/RedMew pull request #1304
Opened 2022-03-18 09:21 UTC by Jayefuu

…leader

Quicker and better than using the vanilla spidertron remote behaviour.

2022-03-18 16:06 UTC, grilledham requested changes
I haven't play tested it yet, but I looked through the code and have some suggestions.

2022-03-18 16:06 UTC, grilledham commented on features/spidertron_group_control.lua
> +                text = '0 [img=item.spidertron] found',
Use localised string. Also maybe "No [img=item.spidertron] found" instead of 0.

2022-03-18 16:06 UTC, grilledham commented on features/spidertron_group_control.lua
> +        local spidertrons = spider_army[player.name]
`spidertrons` could be `nil` here. Do we want to detect that and print a helpful message, like select the the spiders to follow first?

2022-03-18 16:06 UTC, grilledham commented on features/spidertron_group_control.lua
> +                    spidertrons[i] = {} -- remove a spidertron from the table of found entities if the player isn't the last user. Anti-grief.
Might make more sense to build a new array of `allowed_spidertrons` instead. Then your count below wouldn't be wrong

2022-03-18 16:06 UTC, grilledham commented on features/spidertron_group_control.lua
> +            text = '+'..#spidertrons..' [img=item.spidertron]',
Use localised string

2022-03-19 08:34 UTC, Jayefuu commented on features/spidertron_group_control.lua
> +            text = '+'..#spidertrons..' [img=item.spidertron]',
This one doesn't need a localised string. It's an icon and a number.

2022-03-19 08:47 UTC, Jayefuu commented on features/spidertron_group_control.lua
> +            text = '+'..#spidertrons..' [img=item.spidertron]',
Oh you meant the lines above. Got it

2022-03-19 12:21 UTC, grilledham commented on features/spidertron_group_control.lua
> +            text = '+'..#spidertrons..' [img=item.spidertron]',
I did mean this line. I was actually just saying it because the type supports localised strings. But what if in a different culture '+' should be something else.

2022-03-19 20:42 UTC, grilledham requested changes

2022-03-19 20:42 UTC, grilledham commented on features/spidertron_group_control.lua
> +                    spidertrons_valid[i] = spidertron
```suggestion
                    spidertrons_valid[#spidertrons_valid + 1] = spidertron
```
We can't use `i` because it could create gaps in the `spidertrons_valid` array which would cause the count to be incorrect.

2022-03-19 20:42 UTC, grilledham commented on features/spidertron_group_control.lua
> +            --cursor_stack.label = {{'spidertron_group_control.spiders_selected_success',7}}
Remove the commented out code

2022-03-19 22:10 UTC, Jayefuu commented on features/spidertron_group_control.lua
> +                    spidertrons_valid[i] = spidertron
So if I do:
local test = {}
test[1] = 7
test[709] = 7

Then #test is 709 ?

But if I do 
local test = {}
test["one"] = 7
test["709"] = 7

Then #test is 2?

*sigh* I hate lua

2022-03-19 22:32 UTC, grilledham commented on features/spidertron_group_control.lua
> +                    spidertrons_valid[i] = spidertron
> So if I do:
local test = {}
test[1] = 7
test[709] = 7
Then #test is 709 ?

`#test` would be 1

> But if I do
local test = {}
test["one"] = 7
test["709"] = 7
Then #test is 2?

#test would be 0.

`#` is the number of consecutive entries from 1 .. n.
0, negative numbers, string and other keys are ignored.

2022-03-20 12:19 UTC, grilledham requested changes

2022-03-20 12:19 UTC, grilledham commented on features/spidertron_group_control.lua
> +                spidertron.follow_target = target_spider[1]
Just noticed we need to check `spidertron` is valid here. E.g. you select a spidertron it is then mined or dies, then you try and target another spidertron.
![image](https://user-images.githubusercontent.com/10003572/159161651-eff339b7-399c-488a-a3d4-58123e077fff.png)

2022-03-20 12:19 UTC, grilledham commented on features/spidertron_group_control.lua
> +        local spidertrons = spider_army[player.name]
You should move this line `local spidertrons = spider_army[player.name]` above
`if not spider_army[player.name] then` so you can use it there, instead of doing the same table lookup twice.

2022-03-20 12:19 UTC, grilledham commented on map_gen/maps/crash_site/commands.lua
> +            if item.name=='spidertron_planner' then
I'd combine this with the previous if.

2022-03-20 16:36 UTC, Jayefuu commented on features/spidertron_group_control.lua
> +                    spidertrons_valid[i] = spidertron
Good to know. Thank you.

2022-03-20 19:48 UTC, grilledham approved these changes

2022-03-20 19:49 UTC, merged