Game statistics and player awards for danger ores.
Valansch/RedMew pull request #1305
Opened 2022-03-21 15:18 UTC by Jayefuu

2022-03-21 17:37 UTC, grilledham requested changes
A few suggestions. I haven't play tested it but it mostly looks good.

2022-03-21 17:37 UTC, grilledham commented on features/player_stats.lua
> +ScoreTracker.register(resource_tiles_exhausted_name, {'player_stats.resource_tiles_exhausted'})
Maybe `resources_exhausted_name` instead. Tiles is slightly odd because a resource could take up more than one tile.

2022-03-21 17:37 UTC, grilledham commented on map_gen/maps/danger_ores/modules/restart_command.lua
> +        .. 'Total ore tiles exhausted: '..statistics.resource_tiles_exhausted..'\\n'
Maybe `'Total resources exhausted'`. This would also include non ore resources that are exhausted like oil.

2022-03-21 17:37 UTC, grilledham commented on map_gen/maps/danger_ores/modules/restart_command.lua
> +            if game.entity_prototypes[ore_name].resource_category == 'basic-solid' then
Is `game.entity_prototypes[ore_name]` not just the variable you are discarding in the for loop above?

2022-03-21 17:37 UTC, grilledham commented on map_gen/maps/danger_ores/modules/restart_command.lua
> +                ore_totals_message = ore_totals_message..ore_name:gsub( "-ore", "")..": "..string.format("%.2fM, ",count/1000000)
You could use `format_number` here instead, handles the suffixes for you. See <https://github.com/Refactorio/RedMew/blob/develop/features/gui/score.lua#L9> for an example.

2022-03-21 17:37 UTC, grilledham commented on map_gen/maps/danger_ores/modules/restart_command.lua
> +        ore_totals_message = ore_totals_message:sub(1, -3)..')'
Maybe it bothers me more than it should given this is a danger ore map, but in theory the number of ore prototypes could be zero, which would make this message odd. Feel free to ignore.

2022-03-25 08:52 UTC, Jayefuu commented on map_gen/maps/danger_ores/modules/restart_command.lua
> +        .. 'Total ore tiles exhausted: '..statistics.resource_tiles_exhausted..'\\n'
I chose to exclude oil because it's never really exhausted, just reaches a minimum output. I want this to be more a figure of how much space has been cleared.

2022-03-25 08:53 UTC, Jayefuu commented on map_gen/maps/danger_ores/modules/restart_command.lua
> +        ore_totals_message = ore_totals_message:sub(1, -3)..')'
Will do :D

2022-03-25 09:20 UTC, Jayefuu commented on features/player_stats.lua
> +ScoreTracker.register(resource_tiles_exhausted_name, {'player_stats.resource_tiles_exhausted'})
Good point. Fixed.

2022-03-25 09:32 UTC, Jayefuu commented on map_gen/maps/danger_ores/modules/restart_command.lua
> +                ore_totals_message = ore_totals_message..ore_name:gsub( "-ore", "")..": "..string.format("%.2fM, ",count/1000000)
I looked at the documentation for Util.format_num = function(amount, decimal, prefix, neg_prefix). It doesn't look as clear to use to me as the C style string.format which is pretty universal. What I've done works and I think is clearer.

2022-03-25 09:32 UTC, Jayefuu commented on map_gen/maps/danger_ores/modules/restart_command.lua
> +            if game.entity_prototypes[ore_name].resource_category == 'basic-solid' then
Doh. Thank you. Fixed.

2022-03-25 17:25 UTC, grilledham commented on map_gen/maps/danger_ores/modules/restart_command.lua
> +                ore_totals_message = ore_totals_message..ore_name:gsub( "-ore", "")..": "..string.format("%.2fM, ",count/1000000)
Wouldn't `string.format("%.2fM, ",count/1000000)` just become `format_number(count, true)`.
The advantage of format_number is it picks the right suffix based on the magnitude.

Not sure where you found that documentation `format_number` is `function util.format_number(amount, append_suffix)`

2022-03-30 11:09 UTC, Jayefuu commented on map_gen/maps/danger_ores/modules/restart_command.lua
> +                ore_totals_message = ore_totals_message..ore_name:gsub( "-ore", "")..": "..string.format("%.2fM, ",count/1000000)
Oh! That's cool.

2022-04-01 11:22 UTC, grilledham approved these changes

2022-04-01 11:22 UTC, merged