Add no_bots preset for crashsite
Valansch/RedMew pull request #1307
Opened 2022-03-25 18:14 UTC by Soggs

The preset removes access to construction and logistic bots on crashsite

2022-03-25 18:29 UTC, grilledham requested changes

2022-03-25 18:29 UTC, grilledham commented on map_gen/maps/crash_site/scenario_no_bots.lua
> +local function init(config)
config could have a flag for no_bot_outposts. Then we just don't add `mini_t1_robotics_factory` to `mini2` and `mini3` tables. The order in the tables doesn't matter, so it could be the last entry.

Is that the only different in this file compared to scenario.lua, would that allow us to avoid the duplication?

2022-03-25 18:29 UTC, grilledham commented on map_gen/maps/crash_site/presets/no_bots.lua
> +    scenario_name = 'crashsite',
We should also add the preset to scenario_templates. Whatever you could that preset, probably "crashsite-no-bots", should be the name here.

2022-03-25 18:29 UTC, grilledham commented on map_gen/maps/crash_site/presets/no_bots.lua
> +ScenarioInfo.set_map_name('Crashsite')
Change the name here too.

2022-04-03 05:16 UTC, Soggs commented on map_gen/maps/crash_site/scenario_no_bots.lua
> +local function init(config)
So had a moment to think and I remembered when going over it, that it might be an idea to generally move the list of outposts that get loaded into the config. So we are generally able to alter outposts based on config. Partially because it might interesting to have different levels of allowed bots. This current preset is literally no bots but maybe we only want to prohibit logistic bots.

Also would leave for presets like no science outposts or no military outposts.

2022-04-03 10:45 UTC, grilledham commented on map_gen/maps/crash_site/scenario_no_bots.lua
> +local function init(config)
Sounds like a good idea, more effort though. I'll leave it up to you if you want to do that.

2022-06-12 23:20 UTC, Soggs commented
I think I have everything updated. In the mean time I did add a second preset, that is just personal construction bots instead of no bots at all.

2022-06-13 18:23 UTC, grilledham commented on map_gen/maps/crash_site/scenario_no_bots.lua
> +local function init(config)
I would prefer not to have a duplicate scenario file. I think adding a flag to config and not adding the bot outposts would be easy to do.

2022-06-25 12:26 UTC, grilledham approved these changes

2022-06-25 12:27 UTC, merged