Add new DangerOre presets
Valansch/RedMew pull request #1383
Opened 2023-10-27 23:40 UTC by RedRafe

(I'm back)

Add new DangerOre modded maps with the following mods:
- BZ mods
- Exotic Industries
- Omnimatter
- Industrial Revolution 3
- Pyanodon

[Here](https://www.notion.so/RedMew-project-9195bb3f1555452a8e35f59d0d72f9e9#0ad66d25f52c408c91d80ac4b2df24a5) is the full preview.

This is the data part: [redmew-data](https://github.com/RedRafe/redmew-data)

2023-10-28 15:20 UTC, grilledham requested changes
Some minor changes, then I think this is good to go.
Also I've uploaded all the mod packs to the server.

2023-10-28 15:20 UTC, grilledham commented on map_gen/maps/danger_ores/modules/biter_drops_exotic_industries.lua
> +end
I don't think using `map_gen.shared.random` like that is desync safe in multiplayer. I think this can be easy converted to use `math.random` instead.

Also in my suggestion I changed the for loop range to `1, weight` because for loop ranges are inclusive so `0, weight+1` would be two extra?

```suggestion
local weights = {
  ['ei_energy-crystal'] =  10,
  ['ei_gold-chunk']     =  10,
  ['ei_alien-resin']    = 150,
  ['ei_alien-seed']     =   4,
  ['ei_alien-beacon']   =   1,
}

local weighted_table = {}
for item, weight in pairs(weights) do
  for _ = 1, weight do
    weighted_table[#weighted_table + 1] = item
  end
end

local function draw_random()
  return weighted_table[math.random(#weighted_table)]
end
```

2023-10-28 15:20 UTC, grilledham commented on map_gen/maps/danger_ores/presets/danger_ore_omnimatter.lua
> +    { count =  1, name = 'burner-omnitraction' },
'burner-omnitraction' isn't a valid item name?

![image](https://github.com/Refactorio/RedMew/assets/10003572/42d020d2-6222-4b57-a060-8a6e9e42d707)

2023-10-28 15:20 UTC, grilledham commented on map_gen/maps/danger_ores/modules/concrete_on_landfill_omni.lua
> +    local brush_tools = {['omnite-refined-concrete'] = true,} -- , ['refined-hazard-concrete'] = true}
Is this the only way this differs from `concrete_on_landfill.lua`? If so maybe we should pass in `{['omnite-refined-concrete'] = true}` by the `config` and have it default to `{['refined-concrete'] = true}`.

2023-10-28 15:20 UTC, grilledham commented on map_gen/maps/danger_ores/modules/map_without_gaps.lua
> +    local function ore_builder(ore_name, amount, ratios, weighted)
Is `ore_builder` the only way this differs from `map.lua`? If so, could we add this version of `ore_builder` to the module folder called something like `ore_builder_without_gaps.lua` then pass it in through `config`.

2023-10-28 15:20 UTC, grilledham commented on map_gen/shared/builders.lua
> +end
```suggestion
--- Loops through the shapes, if any shape is able to place any entities,
--- it'll return that tile. Otherwise, false is returned.
function Builders.any_entity_pattern(pattern)
    return function(x, y, world)
        for index, shape in pairs(pattern or {}) do
            local tile = shape.shape(x, y, world)
            if tile and tile.entities then return tile end
        end
        return false
    end
end
```

2023-10-28 15:20 UTC, grilledham commented on map_gen/maps/danger_ores/modules/map_poll.lua
> +    krastorio_mod_pack = 'danger_ore_krastorio2',
Just bumping the mod pack version.

```suggestion
    krastorio_mod_pack = 'danger_ore_krastorio3',
```

2023-10-28 21:56 UTC, RedRafe commented on map_gen/maps/danger_ores/modules/biter_drops_exotic_industries.lua
> +end
Yeah it totally makes sense. I don't even know where the 0/+1 came from

2023-10-28 21:59 UTC, RedRafe commented on map_gen/maps/danger_ores/modules/concrete_on_landfill_omni.lua
> +            inventory.insert {name = 'omnite-refined-concrete', count = refund_count}
@grilledham this and L52 are the other places where the vanilla concrete was hardcoded. I guess we could pass as param `replaced_tile` alongside `replace_tile`

2023-11-09 16:57 UTC, grilledham approved these changes
Fantastic work as always! Thanks for making the changes.

2023-11-09 17:00 UTC, merged