Reformatted entire codebase
Valansch/RedMew pull request #394
Opened 2018-11-18 16:53 UTC by Valansch

Style settings are 4 spaces as tabs, unix line endings and 120 character lines.

Please dont hold back on any criticism.

2018-11-18 16:56 UTC, SimonFlapse commented on features/autodeconstruct.lua
> +Event.add(defines.events.on_resource_depleted, on_resource_depleted)
Is the same event added two times here?

2018-11-18 16:56 UTC, Valansch commented on features/autodeconstruct.lua
> +Event.add(defines.events.on_resource_depleted, on_resource_depleted)
something happend here and i dont know what

2018-11-18 16:57 UTC, SimonFlapse commented on features/autodeconstruct.lua
> +Event.add(defines.events.on_resource_depleted, on_resource_depleted)
Luckily it's at the top

2018-11-18 16:59 UTC, SimonFlapse commented on features/gui/player_list.lua
> +local symbol_desc = ' â–¼'
Does this still work?

2018-11-18 16:59 UTC, SimonFlapse commented on features/gui/poll.lua
> +    local forward_button = poll_viewer_top_flow.add {type = 'button', name = poll_view_forward_name, caption = 'â–¶'}
Same here, does it still work?

2018-11-18 17:00 UTC, Valansch commented on features/gui/blueprint_helper.lua
> +            caption = 'Flip Horizontal â‡„'
Interesting

2018-11-18 17:04 UTC, SimonFlapse commented on features/gui/tasklist.lua
> +            caption = 'â–¼',
Some more here

2018-11-18 17:05 UTC, SimonFlapse commented on features/reactor_meltdown.lua
> +--a reactors loses 2 damage per second at 1000Â°C
Minor thing in comment

2018-11-18 17:05 UTC, SimonFlapse commented on features/reactor_meltdown.lua
> +            string.format('Reactor at %sÂ°C', math.floor(reactor.temperature)),
Another

2018-11-18 17:48 UTC, linaori requested changes
While a lot of it looks alright, there are a few points that I'd like to see fixed before merging. This style _extremely_ verbose, making some code really hard to read and keep track of indents. At other points it actually will hurt, like no trailing commas.

I don't mind single vs double comma/4 space indents as fixed, but this change is too much without having a CI that blocks PRs and having the ability to locally fix it. This however, would hurt contributions by people who don't have the toolsets. A codestyle is only as good as the way it's being enforced, otherwise it's pointless. 

I think having just a `.editorconfig` for the spaces and newlines will be sufficient. On top of that we can make some basic rules such as single vs double quotes, but this (as proven) will already be hard to enforce.

2018-11-18 17:48 UTC, iltar commented on map_gen/Diggy/AlienEvolutionProgress.lua
> +        cache = {}
can we please keep this? It reduces diffs when adding new items and copy-pasting will less often result into errors

2018-11-18 17:48 UTC, iltar commented on features/train_saviour.lua
> +                    ')\nEach ' ..
This needs a fix >.<

2018-11-18 17:48 UTC, iltar commented on map_gen/Diggy/Feature/DiggyHole.lua
> +                                noise2 < cluster.noise_settings.discriminator_threshold
this if-statement is hard to read with this odd indent

2018-11-18 17:48 UTC, iltar commented on map_gen/Diggy/Feature/RefreshMap.lua
> +                        {
this insert takes up 7 lines instead of just 1, anything we can do about this? I don't mind splitting code on multiple lines, but this is a bit too much

2018-11-18 17:48 UTC, iltar commented on map_gen/Diggy/Feature/ScatteredResources.lua
> +                                 then
this then is indented 1 space further than the if, making it hard to find out what the indent should be

2018-11-18 18:20 UTC, plague006 commented
>120 character lines

I tried that locally for a time and felt it was really restrictive. I think we should recommend that people not have lines longer than they need be, but I don't think we should autoformat for it nor enforce it.

----

I don't think we need or want CI enforcing a style. As @iltar mentioned it would be restrictive. However, I think we can recommend a style / have a style guide without enforcing it on people who contribute infrequently. If the core team sticks to a style then we can just manually fix PRs as they come.

2018-11-20 11:57 UTC, Valansch commented
All points taken. This PR was simply letting the reformatter run and seeing what happends. Since this resulted in a styleguide #396 alot of refactoring has been done by @plague006 i will close this PR.

2018-11-20 11:57 UTC, closed without merging