Finalize styleguide
Valansch/RedMew pull request #396
Opened 2018-11-18 18:38 UTC by plague006

I recommend we come to a consensus on a style before changing the style of everything in https://github.com/Refactorio/RedMew/pull/394.

Included is what the consensus has generally skewed towards and some fairly standard rules.

2018-11-18 18:43 UTC, SimonFlapse commented on docs/STYLEGUIDE.md
> +* Include at least a brief one-line summary in a luadoc (a comment with 3 dashes `---`) before each function
What about the tags? If your IDE supports it it should generate @param tags when starting luadoc with 3 dashes

2018-11-18 18:52 UTC, plague006 commented on docs/STYLEGUIDE.md
> +* Include at least a brief one-line summary in a luadoc (a comment with 3 dashes `---`) before each function
I think having a full luadoc would be nice, how should we word it so that it's clear a full luadoc would be nice but is unnecessary while a one-line luadoc summary is expected?

2018-11-18 18:55 UTC, SimonFlapse commented on docs/STYLEGUIDE.md
> +* Include at least a brief one-line summary in a luadoc (a comment with 3 dashes `---`) before each function
I think the at least part is perfect. Maybe encourage a `@param` description and `@return` if the function returns for non-local functions. That'll help a lot. So much yet to learn and figure out because this is absent.

2018-11-18 19:19 UTC, plague006 commented
Link to see what it looks like in-browser: https://github.com/plague006/RedMew/blob/style/docs/STYLEGUIDE.md

2018-11-18 19:20 UTC, SimonFlapse commented
It gives us something to continue working on.

2018-11-18 19:45 UTC, grilledham approved these changes

2018-11-19 09:16 UTC, iltar commented
Can we add a rule to always have the last item of table, when split over multiple lines, have a trailing comma? This makes copy-paste issues when adding new lines a lot less likely and reduces the diffs slightly:
```diff
{
    'item1',
-    'item2'
+    'item2',
+    'item3'
}
````
vs
```diff
{
    'item1',
    'item2',
+    'item3',
}
````
A lot of IDEs have a "duplicate line", which simply duplicates it, but missing the last `,`, it will have 2 lines in a row missing a `,`, which sometimes breaks formatting and can be quite annoying. A lot of inexperienced people who use tools like notepad++ might not even notice the missing `,` and simply run into errors and ask us what's wrong.

2018-11-20 11:52 UTC, Valansch requested changes
Like most of it. I just have one minor issue

2018-11-20 11:52 UTC, Valansch commented on docs/STYLEGUIDE.md
> +* Include at least a brief one-line summary in a LuaDoc (a comment with 3 dashes `---`) before each function
I don't like the wording here. Could you change it to say something like "each public/module function". I disagree that every function needs a LuaDoc entry.

2018-11-20 11:54 UTC, iltar commented on docs/STYLEGUIDE.md
> +* Include at least a brief one-line summary in a LuaDoc (a comment with 3 dashes `---`) before each function
It doesn't necessarily need a description, but it would be nice to have parameter information documented for all public facing functions (I don't care as much about private)

2018-11-20 11:58 UTC, Valansch commented on docs/STYLEGUIDE.md
> +* Include at least a brief one-line summary in a LuaDoc (a comment with 3 dashes `---`) before each function
I agree. That was what i was trying to say :)

2018-11-20 14:42 UTC, plague006 commented on docs/STYLEGUIDE.md
> +* Include at least a brief one-line summary in a LuaDoc (a comment with 3 dashes `---`) before each function
Will make that change change.

2018-11-20 15:39 UTC, Valansch commented on docs/STYLEGUIDE.md
> +* Include at least a brief one-line summary in a LuaDoc (a comment with 3 dashes `---`) before each function
Very good good.

2018-11-21 13:34 UTC, Valansch approved these changes

2018-11-21 13:35 UTC, merged