Shift command logging to free_item_logging, fix cases of server as actor
Valansch/RedMew pull request #427
Opened 2018-11-22 07:22 UTC by plague006

Kept logging of jail since free_item_logging won't catch jailing through the GUI.

2018-11-22 22:07 UTC, Valansch commented on features/custom_commands.lua
> +        if (player and global.walking[player.index] == true) or global.walking[target.index] == true then
== true can be omitted

2018-11-22 22:07 UTC, Valansch requested changes
Very nice, just one minor thing. Dismiss this and merge if you disagree with my suggestion

2018-11-22 23:07 UTC, plague006 commented
Nah you're totally right, it's cleaner and more sensible.

2018-11-23 17:06 UTC, Valansch approved these changes

2018-11-23 17:07 UTC, merged