Fixed antigrief desyncs
Valansch/RedMew pull request #467
Opened 2018-11-26 12:06 UTC by Valansch

2018-11-26 12:10 UTC, iltar commented on map_gen/Diggy/Feature/Antigrief.lua
> +            jailed_players[player_index] = true
This is never removed from the table, would it make sense for that to happen?

2018-11-26 23:50 UTC, Valansch commented on map_gen/Diggy/Feature/Antigrief.lua
> +            jailed_players[player_index] = true
If a person is jailed once they will never be jailed again. This is intended that way yes. If an admin already dealt with it and it happends again then it will most likely be an accident.

2018-11-27 07:56 UTC, linaori approved these changes

2018-11-27 21:53 UTC, mheguy requested changes
In testing:

```
"Error while running event level::on_entity_died (ID 4)
LuaEntity doesn't contain key index.
stack traceback:
...ntly-playing/map_gen/Diggy/Feature/DiggyCaveCollapse.lua:249: in function 'handler'
/factorio/6/temp/currently-playing/utils/event.lua:16: in function 'call_handlers'
/factorio/6/temp/currently-playing/utils/event.lua:30: in function </factorio/6/temp/currently-playing/utils/event.lua:28>"
```

In addition, when a cave collapse killed a player there was a corpse and a character standing there unattached to a player. The player then respawned as expected.

2018-11-28 08:15 UTC, iltar commented
I think that's the bug I fixed in 470 yesterday while we were testing: https://github.com/Refactorio/RedMew/blob/6b589fb8f6d33a8508b52fcf0d4aeed7782b30ed/map_gen/Diggy/Feature/DiggyCaveCollapse.lua#L248

2018-11-28 11:56 UTC, mheguy approved these changes
Both bugs went away after rebasing the branch to dev. Merging with my thanks.

2018-11-28 11:56 UTC, merged