New evolution calculation and item balancing
Valansch/RedMew pull request #480
Opened 2018-11-29 18:58 UTC by SimonFlapse

2018-11-29 18:59 UTC, SimonFlapse commented on map_gen/Diggy/Feature/Experience.lua
> +local function on_void_removed(event)
True

2018-11-29 19:04 UTC, plague006 commented on map_gen/Diggy/Feature/Experience.lua
> +local function on_void_removed(event)
You can use `_` for unused data. That way sticker will leave you alone and people reading it will understand it's intentional and not a mistake.

2018-11-29 19:05 UTC, linaori commented on map_gen/Diggy/Feature/AlienSpawner.lua
> +    game.map_settings.enemy_evolution.time_factor = 0.000008
Where's pollution disabled?

2018-11-29 19:05 UTC, linaori commented on map_gen/Diggy/Feature/Experience.lua
> +local count = -189
What's this local for? I think it would cause desyncs

2018-11-29 19:06 UTC, iltar commented on map_gen/Diggy/Feature/Experience.lua
> +local function on_void_removed(event)
In case of unused arguments, you can even omit them. Lua won't complain if you define less parameters than passed
```lua
local function foo() end
foo(1, 2, 3) -- works
```

2018-11-29 19:06 UTC, SimonFlapse commented on map_gen/Diggy/Feature/AlienSpawner.lua
> +    game.map_settings.enemy_evolution.time_factor = 0.000008
Oh yeah that's what I forgot. You can disabled it in the mapgen settings before generating the map. Not sure how else to do it

2018-11-29 19:08 UTC, SimonFlapse commented on map_gen/Diggy/Feature/Experience.lua
> +local count = -189
Could be, haven't checked with more than one player. It's used to prevent the table lookup further down at every void removed, but only every 50th removed. And since the starting zone removed 189 i'm trying to prevent this from affecting the evolution

2018-11-29 19:08 UTC, SimonFlapse commented on map_gen/Diggy/Feature/Experience.lua
> +local count = -189
It is actually redundant now since everything below level 1 just defaults to 0.1 evolution

2018-12-06 11:10 UTC, Valansch requested changes
See @iltar s comments

2018-12-21 20:07 UTC, SimonFlapse commented
Outdated, closing this PR. I need to reevaluate the balancing needs.

2018-12-21 20:07 UTC, closed without merging