Added 'rotten_apples' map preset and supporting files.
Valansch/RedMew pull request #494
Opened 2018-12-01 08:30 UTC by Jayefuu

2018-12-01 08:42 UTC, mheguy requested changes
`no_spawners` seems to be the same as tetris, it's just missing the table `names` with the 2 types of spawners listed.

2018-12-01 08:42 UTC, plague006 commented on map_gen/presets/rotten_apples.lua
> +            {force = 'enemy', name = names, position = {world.x, world.y}}
This one is an actual problem, feel free to ignore the others.

2018-12-01 08:48 UTC, Jayefuu commented on map_gen/presets/rotten_apples.lua
> +            {force = 'enemy', name = names, position = {world.x, world.y}}
Updated, thank you.

2018-12-01 11:37 UTC, iltar commented on map_gen/presets/rotten_apples.lua
> +            force.set_ammo_damage_modifier(type, current_m + (mod * mult))
considering `force.get_ammo_damage_modifier` and `force.set_ammo_damage_modifier` are called in a loop, I recommend to extract the references to those functions to just above the loop, meaning it won't have to talk to the factorio API to get these functions

2018-12-01 11:37 UTC, iltar commented on map_gen/presets/rotten_apples.lua
> +        world.surface.find_entities_filtered(
~~`local find_entities_filtered = world.surface.find_entities_filtered` would reduce overhead here.~~ Additionally you could use pairs instead of ipairs, as it's faster. If you want to go for speed, use a for loop with a count

There are some more places where you can do this

Edit: nvm, didn't see that it was _in_ the ipairs

2018-12-01 22:18 UTC, Jayefuu commented on map_gen/presets/rotten_apples.lua
> +        world.surface.find_entities_filtered(
It doesn't run very often and I'm not sure I'll ever reuse the code. It wasn't a particularly fun mechanic, not with the balance we had anyway.

2018-12-01 22:19 UTC, Jayefuu commented on map_gen/presets/rotten_apples.lua
> +            force.set_ammo_damage_modifier(type, current_m + (mod * mult))
If you have time, please could you make this change so I've got an example of the correct way to do it the next time?

2018-12-01 22:51 UTC, iltar commented on map_gen/presets/rotten_apples.lua
> +            force.set_ammo_damage_modifier(type, current_m + (mod * mult))
Example:
```lua
local function modify_damage(force, mult)
    local get_ammo_damage_modifier = force.get_ammo_damage_modifier
    local set_ammo_damage_modifier= force.set_ammo_damage_modifier
    for type, mod in pairs(player_ammo_research_modifiers) do
        local current_m = get_ammo_damage_modifier(type)
        if (current_m + (mod * mult))<=-0.9 then
            set_ammo_damage_modifier(type, -0.9)
        else
            set_ammo_damage_modifier(type, current_m + (mod * mult))
```
Every time force.<something> is called, it has to make an API call to the object in Factorio (C++), meaning you have some overhead each time you call it. This way the reference to the function is stored locally and you only call it when initially fetching it. Afterwards you're calling that local variant, reducing overhead.

2018-12-03 03:27 UTC, mheguy approved these changes

2018-12-03 10:21 UTC, merged