Added biter_lane_wars PVP files.
Valansch/RedMew pull request #513
Opened 2018-12-05 13:48 UTC by Jayefuu

2018-12-05 13:52 UTC, linaori approved these changes
I think we can merge this as is and improve on it bit by bit.

2018-12-05 13:52 UTC, iltar commented on map_gen/presets/biter_lane_wars/biter_lane_wars.lua
> +ScenarioInfo.set_map_extra_info('- Send biters to your opponents using the market\n- Earn more gold per wave by sending more biters\n- Defend your smelter at all costs!')
Lua supports multi line strings:
```lua
ScenarioInfo.set_map_extra_info([[- Send biters to your opponents using the market
- Earn more gold per wave by sending more biters
- Defend your smelter at all costs!]])
```

2018-12-05 13:56 UTC, Valansch requested changes

2018-12-05 13:56 UTC, Valansch commented on map_gen/presets/biter_lane_wars/biter_lane_wars.lua
> +local function on_tick(event)
event.tick holds the same information and is faster, as it doesn't need an api call.

2018-12-05 13:56 UTC, Valansch commented on map_gen/presets/biter_lane_wars/biter_lane_wars.lua
> +    if game_tick % wave_duration_ticks == 50 then
since this code is only doing anything ever 50 ticks, remove the on_tick listener please and replace it with Event.on_nth_tick

2018-12-05 13:56 UTC, Valansch commented on map_gen/presets/biter_lane_wars/info.lua
> +    ]]--
No new line on EOF. 
stickler-ci what are you doing, lazy?

2018-12-05 13:56 UTC, Valansch commented on map_gen/presets/biter_lane_wars/market_items.lua
> +]]--
Same here

2018-12-05 13:56 UTC, Valansch commented on map_gen/shared/builders.lua
> +-- Tile a shape in a circular pattern
This change is contained in #514.
Please either close that #514, base this #513 on the #514 or remove this file from this #513 (This would break it until #514 is merged).

2018-12-05 13:57 UTC, Valansch commented
Why does market_items.lua only contain commented out code?

2018-12-05 14:03 UTC, Jayefuu commented
"Why does market_items.lua only contain commented out code?"
Because I know it needs to go there, but not what to wrap it in yet until Linaori rewrites something from Diggy for it.

2018-12-05 16:13 UTC, Jayefuu commented on map_gen/shared/builders.lua
> +-- Tile a shape in a circular pattern
#514 should take precedence as I will use it while lane wars is still being developed in its own branch. I don't know how to make the changes in git you've suggested, I'll speak to @plague006 later and ask him to walk me through it.

2018-12-05 16:42 UTC, Valansch commented on map_gen/shared/builders.lua
> +-- Tile a shape in a circular pattern
Forget about it, ill just deal with the conflict :P 
I will merge this when #514 is merged then.

2018-12-05 16:44 UTC, Jayefuu commented on map_gen/shared/builders.lua
> +-- Tile a shape in a circular pattern
<3

2018-12-05 16:48 UTC, Valansch commented on map_gen/presets/biter_lane_wars/biter_lane_wars.lua
> +    if game_tick % wave_duration_ticks == 50 then
I misread this. In the current config it will run at every (3600th + 50) tick. 3650, 7250 10850... Any reason for this?
I suggest using 3593 or 3607 as those are prime.

2018-12-06 03:04 UTC, plague006 commented on map_gen/presets/biter_lane_wars/info.lua
> +    ]]--
LuaCheck doesn't look at EOF, never has. Poke at it a bit, I'm sure you could find a way to add something to check for EOF newline.

2018-12-06 03:10 UTC, mheguy approved these changes
This just pushes to a branch to work on this project, as such I'm giving this automatic approval.

2018-12-06 03:12 UTC, plague006 commented
I rebased `patch-4` into this (d8335494f3e78366da271717163ba3fa57cca02d). Either way, any merge conflicts can be resolved when this PRs into dev.

2018-12-06 03:12 UTC, merged