Overhauled day_night_cycle, creep_spread, and nightfall. Add Venus map.
Valansch/RedMew pull request #524
Opened 2018-12-08 07:29 UTC by plague006

There are still optimizations to be made, but I felt I needed to PR this sooner rather than later because of how bloated the branch became.

In particular: better threading for both nightfall and terraforming and creating a generic feature out of Venus::world_settings (and likely at the same time pushing all maps to start using a second surface and having `nauvis` become a kind of lobby.

2018-12-08 11:40 UTC, linaori requested changes

2018-12-08 11:40 UTC, iltar commented on map_gen/misc/day_night.lua
> +        error('[DAY_NIGHT] Provided day/night cycle is invalid')
What's `[DAY_NIGHT]` referring to?

2018-12-08 11:40 UTC, iltar commented on map_gen/misc/day_night.lua
> +    if _DEBUG then
These 2 could be merged, or instead, `local Debug = 'utils.debug'` and then `Debug.print('your message')` works too by now. Advantage here is that each message gets a uniquely incremented number in front of it, so that the console doesn't merge the message if posted frequently, and only triggers if `_DEBUG` is true

2018-12-08 11:40 UTC, iltar commented on map_gen/misc/day_night.lua
> +    if math.round(daylight, 2) == math.round((1 - surface.darkness), 2) then
Minor thing, referencing `local round = math.round` in the top of the file will give a raw 30% performance boost in those calls

2018-12-08 11:40 UTC, iltar commented on map_gen/misc/nightfall.lua
> +local lastattack = {0}
You could also do something like:
```lua
local memory = {
    base = {},
    c_index = 1,
    chunklist = {},
    state = 1,
    lastattack = 0,
}
```
This would make it less cumbersome to store scalar values in globals

2018-12-08 11:40 UTC, iltar commented on map_gen/misc/nightfall.lua
> +--- Every tick, choose between searching for bases, preparing an attack, or doing nothing
This sounds very heavy, but in fact it looks like it's 1 chunk per tick. Can you add this to the comment so the next person won't be like "oh wow, this is inefficient!" 😄

2018-12-08 16:23 UTC, mheguy commented on map_gen/misc/day_night.lua
> +        error('[DAY_NIGHT] Provided day/night cycle is invalid')
Just the module that the error is coming from. I guess with `error` it would show that. It's more a holdover from other debug messages where I'm printing.

2018-12-08 16:28 UTC, mheguy commented on map_gen/misc/day_night.lua
> +    if _DEBUG then
Debug.print it is! Awesome. 😄

2018-12-08 16:29 UTC, mheguy commented on map_gen/misc/day_night.lua
> +        error('[DAY_NIGHT] Provided day/night cycle is invalid')
Removed the indicator.

2018-12-08 16:33 UTC, plague006 commented on map_gen/misc/day_night.lua
> +    if math.round(daylight, 2) == math.round((1 - surface.darkness), 2) then
I considered that, but you only set a fixed brightness once a map. If someone ends up abusing it and calling it multiple times I'll happily refactor for performance.

If you feel strongly about it I'll change it, or if you want to commit the change I'll be happy to have it.

2018-12-08 16:33 UTC, plague006 commented on map_gen/misc/nightfall.lua
> +local lastattack = {0}
Funny enough, this would have saved us the desyncs. :D
Covered in bf799718d28e7bd710ef0709c3756509ab2b8b06

2018-12-08 16:40 UTC, plague006 commented on map_gen/misc/nightfall.lua
> +--- Every tick, choose between searching for bases, preparing an attack, or doing nothing
I'm not sure the documentation here is inaccurate. All it does in the `on_tick` call is choose the path. `find_bases` and `biter_attack` are fairly well documented so I would rather not copy+paste the documentation, but I can add a line telling the reader check the definitions of those functions for further documentation?

2018-12-08 17:02 UTC, iltar commented on map_gen/misc/day_night.lua
> +    if math.round(daylight, 2) == math.round((1 - surface.darkness), 2) then
It doesn't matter if it gets called once, I thought it was called more often. Carry on! 👍

2018-12-08 17:02 UTC, iltar commented on map_gen/misc/nightfall.lua
> +--- Every tick, choose between searching for bases, preparing an attack, or doing nothing
That could help already yes! 👍

2018-12-09 15:49 UTC, Valansch commented
Thank you. I will merge this and launch another test soon

2018-12-09 15:50 UTC, merged