Add player_reward, add coins as reward for looking at info
Valansch/RedMew pull request #546
Opened 2018-12-14 04:32 UTC by plague006

Creates a generic player reward utility: pretty straightforward, it's little more than player insert and an optional player print.

Ran into problems with the config since I want `player_rewards_token` to be the market item by default but can't reference the market item since it hasn't been defined yet. Not sure if this is the best way to handle it, I considered setting `player_rewards_token` after the `global.config` table was created, but no matter what it all looks messy.

Info.lua:
Added a mechanic that rewards players for looking at each tab by giving them coins.

Removed the admin/regular check since everyone will want the coins. Removed `draw_main_frame` call from `info::player_create` since it conflicts with recent changed to `player_create.lua`. Removed `welcomed_players` since it wasn't actually called by anything. 

Changed fish_market to keep the coin count the same.

2018-12-14 09:07 UTC, linaori requested changes

2018-12-14 09:07 UTC, linaori commented on utils/player_rewards.lua
> +    return player.insert(reward)
Should this feature add coins the same way the stats tracking does? Same question goes for coins as starting items. It's not an important thing to add, more of a "nice to have"

2018-12-14 09:07 UTC, iltar commented on config.lua
> +    player_rewards_enabled = true,
Can you put this in the following structure?
```lua
player_rewards = {
    enabled = true,
    -- the token to use for rewards
    player_rewards_token = market_item,
    -- rewards players for looking through the info tabs
    info_player_reward = true,
},
```
I've omitted the `if true, will override player_rewards_enabled to true`, as it makes no sense to disable a feature, still configure it, and end up loading it anyway because of this value

2018-12-14 09:07 UTC, iltar commented on features/fish_market.lua
> +    player.insert {name = market_item, count = count}
Should this increase the coin count in the stats tracking?

2018-12-14 09:07 UTC, iltar commented on features/gui/info.lua
> +        rewarded_players = tbl.rewarded_players
Can you change this behavior to be:
 - on player created -> add `[player_index] = true`
 - on awarded -> remove `[player_index] = nil`

By keeping track of only those who still need rewards, we effectively reduce the save size by quite a lot. Storing ~40bytes per item when we have 800 players on a map in total, becomes quite a bit of data to serialize, vs perhaps 200 players that haven't been rewarded yet.

2018-12-14 09:07 UTC, iltar commented on utils/player_rewards.lua
> +Public.give_reward = function(player, amount, message)
This function is effectively returning how many coins have been inserted. In theory this will usually work, as coins can be up to 200k a stack. However, if there's no space, the reward will still be given, despite not being inserted into the inventory

2018-12-14 16:03 UTC, plague006 commented on utils/player_rewards.lua
> +    return player.insert(reward)
Really good suggestion. I had the specific info box use-case in mind when I was designing `player_rewards` and that restricted the rewards I was considering. If we use it for something like quests, listing the earnings in stats becomes important.

2018-12-14 16:26 UTC, mheguy commented on config.lua
> +    player_rewards_enabled = true,
Your structure is much better/makes more sense and is now in place. I also agree with the whole override thing. I've correspondingly changed code in info/player_rewards to 1) not override the setting and 2) removed code specific to info_rewards from player_rewards itself.

2018-12-14 16:33 UTC, plague006 commented on features/fish_market.lua
> +    player.insert {name = market_item, count = count}
I think because it is such a small, fixed, and universal amount it's not worth bothering with. But if someone else wants to write the commit I also wouldn't oppose it.

2018-12-14 16:36 UTC, plague006 commented
In testing I noticed coins earned (`player_stats::player_coin_earned`) can be negative. I don't know if we want this behaviour or not.

2018-12-14 16:47 UTC, plague006 commented on utils/player_rewards.lua
> +Public.give_reward = function(player, amount, message)
The function intentionally returns the amount of coins inserted, so that any call to it can keep track of how effective the function was.

Let's say we have a reward system for quest rewards:
```
function quest_complete(event)
  actual_reward = give_reward(event.player, reward_quant)
  outstanding_reward = actual_reward < reward_quant
  if outstanding_reward  then
    event.player.print('will try again in 30 secs to give you your reward')
    outstanding_rewards[event.player.index]=outstanding_reward 
    timeout 30 secs
    give_reward(event.player, outstanding_reward, 'giving you the rest of your reward')
  end
end
```

2018-12-14 16:48 UTC, plague006 commented on utils/player_rewards.lua
> +Public.give_reward = function(player, amount, message)
I would rather not handle those cases in the util itself because I feel like rewards can vary greatly. Some you might want the difference spilled, some you might want to try again later, some you might want to ignore.

2018-12-14 17:12 UTC, iltar commented on utils/player_rewards.lua
> +Public.give_reward = function(player, amount, message)
Spilling loot at the player location would be an option

2018-12-14 17:17 UTC, iltar commented
@plague006 if you remove them, it kind of makes sense. You can get coins from someone and then have them removed

2018-12-14 18:10 UTC, plague006 commented on utils/player_rewards.lua
> +Public.give_reward = function(player, amount, message)
Yes, I just would rather let each application choose their own method of handling it.

2018-12-14 18:13 UTC, plague006 commented
Everything except subtracting bits is in the last commit, implementing that will come in the next commit.

Also added an admin command to manually give rewards (added with the reward for blank map text in mind)

2018-12-15 21:08 UTC, plague006 commented
Should be good to go.

2018-12-18 04:04 UTC, plague006 commented on features/gui/info.lua
> +        rewarded_players = tbl.rewarded_players
There is now a check in place such that when a player has gained all possible coins their entry is removed from the table.

2018-12-19 13:56 UTC, merged