Implement server-side color saving
Valansch/RedMew pull request #566
Opened 2018-12-21 01:54 UTC by plague006

When joining server, sets your saved color.
Adds a couple commands for setting and resetting your color server-side. Also enables getting a random color.

Unrelated changes:
If you're running with `_DEBUG` and you're an admin, gain regular status so that you can test commands that require regular status. -_-
Extend `command` to make commands regular_only.
Add `set_and_return` to core utils.

2018-12-21 08:41 UTC, linaori submitted a review, later dismissed

2018-12-21 08:41 UTC, iltar commented on utils/command.lua
>      local admin_only = options.admin_only or false
What if we change this to "minimum permission level required" of sorts and default it to guest? That would solve the problem and we only have to check if your permissions aren't too low. Might have to change the info added to something like "(Regular or higher)" and "(Admin only)" and not showing anything if everyone (regardless of server) may execute it.

2018-12-21 11:12 UTC, grilledham commented
The first time a player joins the welcome message might not have the correct color. We could wait 60 ticks before showing the welcome message to give time for the color to be fetched from the server. Or we print welcome messages in white.
https://github.com/Refactorio/RedMew/blob/d4e7849cd20ef9342f09b231ae39f1110d3b05e1/features/donator_messages.lua#L24

2018-12-21 11:18 UTC, iltar commented
I don't mind a delayed message

2018-12-21 19:32 UTC, plague006 commented
Right right, because retrieving from the server isn't same-tick. Yeah a delay would be totally cool in my book.

2018-12-21 19:54 UTC, plague006 commented on utils/command.lua
>      local admin_only = options.admin_only or false
That would seem to contradict https://github.com/Refactorio/RedMew/pull/506 where it was established that each rank should be modular and not hierarchical.

2018-12-25 00:45 UTC, plague006 commented
No luacheck on mac laptop so stickler is getting a workout. :D

2019-01-01 16:23 UTC, Valansch requested changes

2019-01-01 16:23 UTC, Valansch commented on utils/command.lua
> +    ['regular_only'] = 'Set this to true if only regulars may execute this command',
I would change lines 16 and 17 to:

['requires_regular'] = 'Set this to true if only players with rank regulars may execute this command'
['requires_admin'] = 'Set this to true if only players with rank admin may execute this command'

Equally at all occurrences. This way we don't violate #506. The word "only" is a bit confusing here. I know what you mean by "regular" and "non-regular", but i don't think its 100% clear that and admin for example is also always a regular and that someone with donator and regular rank is indeed also a regular.

2019-01-01 21:54 UTC, plague006 commented on utils/command.lua
> +    ['regular_only'] = 'Set this to true if only regulars may execute this command',
https://github.com/Refactorio/RedMew/issues/610 aims to do just that. But because #576 and #566 require the same changes it would be much easier for me to work on `command` once those two PRs are merged. Or to put it a different way: if I try to refactor `plague:color`, `plague:overhaul_commands`, and `refactorio:dev` I'm quite certain I'll make a mess of one, if not all, of them.

2019-01-01 22:14 UTC, Valansch commented on utils/command.lua
> +    ['regular_only'] = 'Set this to true if only regulars may execute this command',
Well good then.

2019-01-01 22:14 UTC, Valansch approved these changes

2019-01-02 13:42 UTC, merged