Tetris
Valansch/RedMew pull request #605
Opened 2018-12-29 01:21 UTC by Valansch

Here we go! :D
Working on more luadoc...
#582

2018-12-29 01:22 UTC, Valansch commented on map_gen/combined/tetris/control.lua
> +    if _DEBUG then
You know nothing stickler

2018-12-29 01:23 UTC, Valansch commented on map_gen/combined/tetris/tetrimino.lua
> +    local insert = insert --Intentionally shadowing upvalue
Intentional.

2018-12-29 01:26 UTC, Valansch commented on map_gen/combined/tetris/control.lua
> +    if _DEBUG then
You still know nothing.

2018-12-29 01:34 UTC, plague006 commented on map_gen/combined/tetris/control.lua
> +    if _DEBUG then
you sure about that? I see an empty definition
`primitives.winner_option_index =`

2018-12-29 01:50 UTC, plague006 commented on map_gen/combined/tetris/control.lua
> +    game.print('Pausing...')
In testing, I didn't realize the pause was due to inactivity. Making that clear would be helpful.

2018-12-29 01:50 UTC, plague006 commented on map_gen/combined/tetris/tetrimino.lua
> +        game.print(serpent.line(sequence))
Debug code printing during live play

2018-12-29 02:12 UTC, plague006 commented
Could really benefit from map info.
The magnifying glass icon's use is unclear (it seemingly does nothing).
Removing vote retains the number in the icon.
Removing vote seems to retain the vote itself: voting move right then clearing vote will move the piece right.
An indicator of some kind that a new piece has been spawned would be nice. Maybe a line in the GUI below the points/score?
The first time you vote a piece to "move down" it seems to ignore that vote and the piece only falls 1 space.

2018-12-29 12:12 UTC, Valansch commented
A new piece has spawned once all buttons are enabled again and the timer is running again. I don't feel we need any more indication of that.

2018-12-29 12:20 UTC, Valansch commented
I cannot reproduce the move down issue, it's working as intended for me.
Magnifying glass changes player zoom, i'll add a tooltip.

2018-12-29 17:03 UTC, linaori commented on map_gen/combined/tetris/control.lua
> +    for candidate, n_votes in ipairs(vote_sum) do
pairs is faster and does the same in factorio

2018-12-29 17:43 UTC, plague006 commented on map_gen/combined/tetris/control.lua
> +    for candidate, n_votes in ipairs(vote_sum) do
I'm curious under what conditions you found pairs faster than ipairs. I've tested previously and found ipairs faster.
Here's a quick test I whipped together for this comment:
![image](https://user-images.githubusercontent.com/10162554/50540847-54937e00-0b67-11e9-87cb-726123b595f0.png)

2018-12-29 18:52 UTC, iltar commented on map_gen/combined/tetris/control.lua
> +    for candidate, n_votes in ipairs(vote_sum) do
As frequently said by Klonan and according to https://springrts.com/wiki/Lua_Performance#TEST_9:_for-loops

2018-12-29 20:13 UTC, plague006 commented on map_gen/combined/tetris/control.lua
> +    for candidate, n_votes in ipairs(vote_sum) do
*shrug*
It's not what the test shows, but honestly avoid ipairs as much as I can since we should be using pairs or manually iterating anyways.

2018-12-30 09:38 UTC, Jayefuu reviewed
Sorry, I don't have time to review this week. From a technical standpoint I'm sure Plague and Lin have you covered. From a gameplay standpoint, nice work getting it running!

2018-12-30 11:10 UTC, linaori requested changes

2018-12-30 11:10 UTC, iltar commented on map_gen/combined/tetris/control.lua
> +            local y = tetri.position.y + 16 * q_y - 14
`local tetri_y = tetri.position.y` on top so it's only called once

2018-12-30 11:10 UTC, iltar commented on map_gen/combined/tetris/control.lua
> +                local tile = tetri.surface.get_tile(x, y)
`local tetri_get_tile = tetri.surface.get_tile` on top for a performance boost

2018-12-30 11:10 UTC, iltar commented on map_gen/combined/tetris/control.lua
> +local function collect_full_row_resources(tetri)
This function has a bunch of calls that will benefit from extracting multiple table access calls to a local

2018-12-30 11:10 UTC, iltar commented on map_gen/combined/tetris/control.lua
> +                surface = game.surfaces.nauvis,
those API calls can be extracted to a local just above the for loop

2018-12-30 11:10 UTC, iltar commented on map_gen/combined/tetris/control.lua
> +        machine.transition(states.moving)
minor indent issue

2018-12-31 23:28 UTC, Valansch commented on map_gen/combined/tetris/control.lua
> +    game.print('Pausing...')
I would instead want a pause button, but that doesn't quite fit in the gui.
Btw if anyone has gui style suggestions i would appreciate them greatly

2019-01-01 01:42 UTC, Valansch commented on map_gen/combined/tetris/control.lua
> +    for candidate, n_votes in ipairs(vote_sum) do
I'm guessing you tested with far too few iteration 80ms is far too short to be significant.
I tested with 100 million iterations and ipairs is consistently get 3% slower than pairs.

But even at 1 million iterations ipairs is still 3% slower.
@iltar i assume you tested on windows?

2019-01-01 01:47 UTC, Valansch commented on map_gen/combined/tetris/control.lua
> +    for candidate, n_votes in ipairs(vote_sum) do
Actually.. I just got the opposite result. 1-3% difference is too small to test reliably. But i think we can agree one way or another to use pairs over ipairs and i=1,... over pairs.

2019-01-01 22:38 UTC, Valansch commented on map_gen/combined/tetris/control.lua
> +            local y = tetri.position.y + 16 * q_y - 14
This is called 4 times. So 6 additional table accesses. About once per minute. There comes a point where readability is more important than unmeasurable performance differences. It remains questionable if this is the case here :thinking:

2019-01-02 08:39 UTC, iltar commented on map_gen/combined/tetris/control.lua
> +            local y = tetri.position.y + 16 * q_y - 14
There shouldn't be a loss of readability when assigning to a local, if anything it would actually make it more readable because you can immediately track where this local is used

2019-01-04 20:06 UTC, plague006 commented on map_gen/combined/tetris/tetrimino.lua
> +local Task = require 'utils.schedule'
Affected by #629
(`schedule` to `task`, `q` to `queue`

2019-01-09 19:54 UTC, linaori approved these changes

2019-01-11 17:23 UTC, mheguy approved these changes

2019-01-11 18:25 UTC, mheguy commented
A tour de force, truly the best among us. Code that will stand the test of time.

2019-01-11 18:25 UTC, merged