Redmew surface
Valansch/RedMew pull request #631
Opened 2019-01-05 09:33 UTC by plague006

## Redmew Surface

Broken up into commits to make review easier. There are 65 files but only 4 files are added and make up this module. `redmew_surface` (hereafter RS) itself does all the work, and there are 3 resource files for the individual aspects of world generation: `map_gen_settings`, `map_settings`, and `difficulty_settings`.

### RS for users

As long as a map hasn't explicitly selected to control an aspect of world generation, a user's choices are respected. Further, a user can also disable RS entirely or the individual aspects of worldgen via config settings.

### RS for devs

RS changes the surface that maps are generated on from `nauvis` to a new surface: `redmew`. It offers a way to acquire the surface name pre-init through `get_surface_name` and allows us to get the surface itself from `get_surface` after init.

```lua
local RS = require 'map_gen.shared.redmew_surface'
local surface = RS.get_surface()
```

These methods are intended for modules that act on a surface without being able to determine which surface to act on.

### RS for map makers

#### Concepts

##### Functions

The strength of RS is its ability to control world generation for maps. We no longer have to forcefully scan for and remove ores and trees or water via LUA. We can now simply disable their placement. However RS doesn't force a map to specify more than it wants/needs. If a map only wants to remove all copper ore generation while leaving all other settings to the user: it can do that.

RS splits worldgen into the 3 components that factorio itself splits them into: map_gen_settings, map_settings, and difficulty_settings.

For each of the 3 components, RS has 2 functions to allow control: an `add` function, and a `set` function.

RS works essentially by overwriting. The base is the user's settings. If we use the `add` function we overwrite only the parts of generation that we explicitly state. For example if a user selects rich resources but a map uses the `add` function to remove all copper: the map will spawn no copper but the others at rich settings.

By contrast, the `set` function ensures all user settings are first overwritten by the default world gen options (ie. the options you get when you create a new world for the first time) and then anything explicitly required will overwrite the default world gen. To use the example from above: user selects rich, map uses `set` to remove all copper: map will spawn no copper but the others at normal settings.

##### Resources

To make things easier on map makers, there are many preset world gen options available to select from. These presets/components are available in 3 resource files named for each of the world gen components: `map_gen_settings.lua`, `map_settings.lua`, and `difficulty_settings.lua`. Each file contains in it tables of varying size/scope and settings. For example `waterworld` in `map_gen_settings.lua` contains a table that ensures nothing but water will spawn. This can be nice for a map that wants to fully create its terrain, ores, and entities.

#### Examples
A world with no: enemies, ores, oil, evolution, pollution, and with a 3x tech cost. The user controls everything else.
```lua
local RS = require 'map_gen.shared.redmew_surface'

local MGSP = require 'resources.map_gen_settings' -- map gen settings presets
local DSP = require 'resources.difficulty_settings' -- difficulty settings presets
local MSP = require 'resources.map_settings' -- map settings presets

RS.add_map_gen_settings({MGSP.enemy_none, MGSP.ore_none, MGSP.oil_none})
RS.add_difficulty_settings({DSP.tech_x3})
RS.add_map_settings({MSP.enemy_evolution_off, MSP.pollution_off})
```
A water world with default map settings but user-selected difficulty:
```lua
local RS = require 'map_gen.shared.redmew_surface'

local MGSP = require 'resources.map_gen_settings' -- map gen settings presets
local MSP = require 'resources.map_settings' -- map settings presets

RS.set_map_gen_settings({MGSP.waterworld})
RS.add_map_settings({MSP.default}) -- the table `default` contains all map_settings so add and set would have the same effect: all user settings will be overwritten
```
A map that wants very high enemies and cliffs, but also wants very specific iron and copper generation. The ore generation is too specific to add to the resource file:
```lua
local RS = require 'map_gen.shared.redmew_surface'
local MGSP = require 'resources.map_gen_settings' -- map gen settings presets
RS.set_map_gen_settings(
    {
        MGSP.enemy_very_high,
        MGSP.cliff_very_high,
        {
            autoplace_controls = {
                ['iron-ore'] = {
                    frequency = 'high',
                    richness = 'very-low',
                    size = 'very-high'
                },
                ['copper-ore'] = {
                    frequency = 'low',
                    richness = 'very-high',
                    size = 'very-low'
                }
            }
        }
    }
)
```

2019-01-05 09:37 UTC, plague006 commented
I'm waking travis up, he'll find errors on every commit because he scans the entire codebase.

2019-01-05 10:55 UTC, iltar commented on map_gen/combined/dimensions.lua
> +            player.print('Wooosh! You are now in the ' .. portal.target_surface.name .. ' dimention.')
dimention -> dimension? :D

2019-01-05 10:55 UTC, iltar commented on map_gen/combined/dimensions.lua
> +local function dim_on_tick()
At some point we might have to improve performance here 😅 Not sure if we've used this map recently, but there are a bunch of things we can improve here

2019-01-05 17:08 UTC, plague006 commented on map_gen/combined/dimensions.lua
> +local function dim_on_tick()
Not for as long as I've been on redmew, so 6-7 months?
Regardless, this is far beyond the scope of this PR and I'm marking this resolved.

2019-01-06 15:05 UTC, grilledham reviewed
I like the difference between `add` and `set` but wonder if the names could be better. `add` to me implies that you can do it multiple times like adding to a list, I assume your thinking is it's like extend. 
But given you have to explain what `add` and `set` do, maybe we should just call them `with_user` and `with_default`

2019-01-06 15:05 UTC, grilledham commented on map_gen/shared/redmew_surface.lua
> +    if global.config.redmew_surface.enabled and global.config.redmew_surface.map_gen_settings then
when is `global.config.redmew_surface.enabled` set to `true`? And if it was `false` why are we still creating the redmew surface?

2019-01-06 15:05 UTC, grilledham commented on map_gen/shared/redmew_surface.lua
> +    -- In general, don't create a table custom for a map, instead just add it to the resource files and call that so that others can make use of it.
>> In general, don't create a table custom for a map ...

That is opinionated, I think people can make custom tables for niche presets if they prefer. Having a resource file full of niche presets could arguably make it harder to read.

2019-01-06 15:05 UTC, grilledham commented on map_gen/shared/redmew_surface.lua
> +--- When placed, locomotives will get a random color
>> --- When placed, locomotives will get a random color

Copy and paste error?

2019-01-06 15:07 UTC, grilledham commented
Overall this is a very cool module which will open up some great possibilities. 👍 

 However there is a lot to go through, so I still haven't finished my review.

2019-01-07 21:37 UTC, plague006 commented on map_gen/shared/redmew_surface.lua
> +    if global.config.redmew_surface.enabled and global.config.redmew_surface.map_gen_settings then
Set to true via config during control initialization.
I don't know why I had it in my head that the surface should be created regardless. Changes to just set `surface_name` to `'nauvis'` if RS is disabled.

2019-01-07 21:51 UTC, plague006 commented on map_gen/shared/redmew_surface.lua
> +--- When placed, locomotives will get a random color
I sure hope so. Thanks for the catch.

2019-01-07 23:22 UTC, plague006 commented on map_gen/shape/infinite_mazes.lua
> +    for _ = 1, copper_ore_count do
I'm assuming this was to correct a linting error for an unused loop variable:
luacheck will also take `i` as a loop variable and not generate a warning if it's unused.

2019-01-08 00:08 UTC, plague006 commented
>I like the difference between `add` and `set` but wonder if the names could be better. `add` to me implies that you can do it multiple times like adding to a list, I assume your thinking is it's like extend. 
But given you have to explain what `add` and `set` do, maybe we should just call them `with_user` and `with_default`

This makes me wonder if there's a benefit to an `add` and a `set`. You're right that the names are sub-optimal since adding with `add` may not have the intended effect since conflicting settings will overwrite one another. For `with_user_settings` and `with_default_settings` properly and accurately describing how they're distinct from one another is also giving me a good bit of difficulty.

My primary issue at this point, is that RS is meant to give map makers more tools while also being very easy to use. I'm wondering if, instead of learning two functions entirely, it isn't just easier to learn 1 function and how to use it in order to take full control. That is, instead of learning `add_map_gen_settings` vs `set_map_gen_settings`, simply learning that by giving `set_map_gen_settings` the `defaults` table from the presets you can override all of a player's options.

I know it's an extra step (ie. adding 1 extra argument to a function call) for map-makers but I think wanting to override *every* option from a user is a rare/niche case.

2019-01-08 00:23 UTC, grilledham commented
I think that makes sense. I would imagine that few maps will want to override the user settings with default. They would either want the user settings or have a particular setting they want to enforce, like no biters.

So starting with user settings and overriding makes sense. And if you really want to start from default settings for whatever reason you can with the default preset.

2019-01-08 08:45 UTC, iltar commented
Isn't it the goal to _overwrite_ specifics? This could be achieved with other solutions as well:

```lua
config.set('map_config.property.in.the.config', 100) -- has to convert the string to nested table indexes
config.set(function(map_config) 
    map_config.property.in.the.config = 100
end)
```

2019-01-08 17:24 UTC, mheguy commented
I'm not completely following your suggestion lin

2019-01-08 17:29 UTC, mheguy commented
https://github.com/Refactorio/RedMew/pull/631/commits/19cbd47b5fc0dd8e16f1029a11a76d46f6c806f8:
The `add` public functions have been removed. However the `set` functions no longer completely overwrite user options. Overwriting all user options remains an option as long as all options are set by the map.
The goal of this is to make the entire module easier to understand by reducing the number of functions while maintaining the same capabilities.

The documentation *should* be updated properly and should make no mention of "set" vs "add" nor should it mention anything about a "default".

2019-01-08 17:48 UTC, iltar commented
@plague006 it's the ability to set parts of the map config without having to expose the whole table

2019-01-09 21:07 UTC, plague006 commented
Made create_redmew_surface public so that if a map wants to delete and re-create the surface, it can do so more easily.

2019-01-12 17:34 UTC, grilledham requested changes
Using `RS.set...` is really easy and everything just works as I'd expect, good job!
I only tried for `set_map_gen_settings` but I assume it works for the others too.

However, I have some questions / concerns about the implementation of redmew_surface.lua.

- Why is `create_redmew_surface()` public, what is the expected use case? Do we expect to have redmew_surface disabled, but still have a module want to create the surface anyway?

- Throwing errors when the `RS.set ...` functions are called twice doesn't seem like a good idea to me. Surely it's possible for two modules to make changes to map settings in a way that doesn't interfere. And if they do interfere is throwing an error better than just letting one module override the other.

- if `global.config.redmew_surface.map_gen_settings = false`  then `set_difficulty_settings()` and `set_map_settings()` don't get called.

- Just a style thing but, there are multiple times in the code where you have `global.config.redmew_surface. ...` Why not make a `local config = global.config.redmew_surface` near the top of the file. 

- In the resource files, I'd be tempted to move the default presets to the top. They are the first thing I looked for to understand the structure of the tables.

2019-01-12 17:34 UTC, grilledham commented on map_gen/shared/redmew_surface.lua
> +        surface_name = 'nauvis'
Wouldn't this cause desyncs. If you change a variable in `on_init` it either has to be in global or you have to make the same change in `on_load`.

2019-01-12 17:34 UTC, grilledham commented on map_gen/shared/redmew_surface.lua
> +local surface_name = 'redmew'
Why is this in the constants section when it is mutated on line 205?

2019-01-12 17:34 UTC, grilledham commented on map_gen/shared/redmew_surface.lua
> +local primitives = {
Do we expect changes to `primitives ` and `data` to happen after `on_init`? If not do they need to be in global?

2019-01-12 20:59 UTC, plague006 commented
On mobile, so formatting will suck:
Create surface public: the config setting should take precedence. I dont have an actual use case in mind for it. I was tooling around and deleted the redmew surface and realized there was no way to recreate it.

Throwing an error: the rationale was that it could create unexpected behaviour unless the author was very careful about things like loading order. 

Can and will localize config, can and will properly handle possible config paths. 

Default at top of resources: I've debated back and forth with myself multiple times. As a doc tool the default at the top is great. As a "big clump of useless text" it slows down searching for coomponents. Would splitting the difference make sense? Throw a comment at the top pointing to the default table at the bottom?

2019-01-12 21:00 UTC, plague006 commented on map_gen/shared/redmew_surface.lua
> +local surface_name = 'redmew'
Will fix, either a leftover in code or in my mins from whenever RS would create a surface no matter what (and the surface name would not change)

2019-01-12 21:00 UTC, plague006 commented on map_gen/shared/redmew_surface.lua
> +local surface_name = 'redmew'
My mind*

2019-01-12 21:03 UTC, plague006 commented on map_gen/shared/redmew_surface.lua
> +local primitives = {
I think if I put data and prim to local, I would move create_surface along with it.

2019-01-12 21:05 UTC, plague006 commented on map_gen/shared/redmew_surface.lua
> +        surface_name = 'nauvis'
I appreciate you phrasing your statement in then form of a questions. 😛 

Surface_name was meant to be constant. When I made this change I didn't think through the consequences. Will fix.

2019-01-15 16:16 UTC, plague006 commented on map_gen/shared/redmew_surface.lua
> +local primitives = {
b6c1b7c changes create_surface back to local and so removes data and most of primitives from the global scope.

2019-01-15 16:16 UTC, plague006 commented on map_gen/shared/redmew_surface.lua
> +local surface_name = 'redmew'
Fixed in b6c1b7c

2019-01-15 16:16 UTC, plague006 commented on map_gen/shared/redmew_surface.lua
> +        surface_name = 'nauvis'
Fixed in b6c1b7c

2019-01-15 16:28 UTC, mheguy commented
Need to fix spawn location/players not spawning on redmew surface.

2019-01-16 17:22 UTC, grilledham approved these changes

2019-01-16 17:54 UTC, plague006 commented
Thanks for polishing my turd grilled! :D
![image](https://user-images.githubusercontent.com/10162554/51268304-cb18e400-198d-11e9-98dc-e38c06e1d02f.png)

2019-01-16 18:44 UTC, merged