Score update
Valansch/RedMew pull request #672
Opened 2019-01-21 20:40 UTC by grilledham

Some updates to the score gui.
- Added total coins spent
- Changed the styles
- Removed global to track rockets launched as you can get that from `force.get_item_launched`

2019-01-23 21:45 UTC, plague006 commented on features/gui/score.lua
> +    local message = 'A satellite has been launched! Total count: ' .. count
I don't know if it's still bad since I don't really play anymore.. but I remember that on high rocket launch count maps the launch spam is kind of a nuisance.

How would you feel about something like:
```lua
 if count < 10 or 
((count % 5) == 0 and count < 75) or 
((count % 25) == 0) then
print
```

2019-01-23 21:55 UTC, plague006 commented on features/player_stats.lua
>  function Public.set_coin_spent(player_index, value)
Curious if you have any kind of hypothetical use case for this or for `set_coin_earned`

2019-01-23 21:55 UTC, plague006 commented on features/player_stats.lua
>  function Public.set_coin_spent(player_index, value)
Curious if you have any kind of hypothetical use case for this or for `set_coin_earned`

2019-01-23 22:32 UTC, plague006 commented on features/gui/score.lua
> +    local entity = event.entity
`event.rocket`

2019-01-23 22:41 UTC, plague006 commented on features/gui/score.lua
> +    count = game.forces.player.get_item_launched('satellite')
If we're only using `player` force launches, we should check that the `player` force launched it.

2019-01-23 22:44 UTC, mheguy requested changes

2019-01-23 22:44 UTC, plague006 commented on features/gui/score.lua
> +    local entity = event.entity
`event.rocket`

2019-01-23 22:45 UTC, grilledham commented on features/player_stats.lua
>  function Public.set_coin_spent(player_index, value)
I added it first when I added all the getter and setters. I later realised that change_coin_spent is a nice to have convenient function.

2019-01-23 22:54 UTC, grilledham commented on features/gui/score.lua
> +    local entity = event.entity
god dammit.
I thought I tested this, but clearly not 😄

2019-01-24 13:39 UTC, grilledham commented
LGTM thanks for making the changes 👍

2019-01-24 13:39 UTC, merged