[Diggy] Restoring buffs every 61 ticks
Valansch/RedMew pull request #686
Opened 2019-01-25 14:41 UTC by SimonFlapse

Suggested solution for #673 

Updates all diggy buffs every 61 ticks. If they have been set to zero, restore the values to the active_modifier value.

This only fixes issues caused by mods changing the force modifiers to zero. 

Closes #673

2019-01-25 14:50 UTC, linaori commented
Have you had the chance to test this with a mod?

2019-01-25 15:21 UTC, SimonFlapse commented
> Have you had the chance to test this with a mod?

Not really, I don't know what else we should do about it since it seems the mods are messing about with the modifiers. However with this players can set the buffs to 0 and it'll revert back to the correct value.

2019-01-25 15:32 UTC, linaori commented on map_gen/Diggy/Feature/Experience.lua
> +    local force = players[#players].force
What about `game.players.force`? Seems less error-prone

2019-01-25 15:34 UTC, grilledham commented on map_gen/Diggy/Feature/Experience.lua
> +    local force = players[#players].force
do you mean `game.forces.player`?

2019-01-25 15:35 UTC, linaori commented on map_gen/Diggy/Feature/Experience.lua
> +    local force = players[#players].force
No, `players.game.force`

2019-01-31 00:49 UTC, plague006 commented
Rebasing + force pushing to get up to date with the lint-free dev head.

2019-02-17 10:17 UTC, SimonFlapse commented
Is this still something we'd be interested in adding to diggy? Or are we looking for another solution/no solution.

2019-02-20 08:55 UTC, plague006 commented on map_gen/Diggy/Feature/Experience.lua
> +    Experience.update_health_bonus(force, 0)
Assuming another mod is constantly trying to reset the values to 0, wouldn't that just create a weird situation where a player's health is constantly fluctuating? Or worse, their inventory.

2019-02-20 08:59 UTC, mheguy requested changes
I'm not sure how to handle the situation as a whole, but we can at least prevent diggy from inflicting a debuff on its players. Edit: my mistake that we wouldn't be creating a debuff, we would just be giving less than the total buff that we should be applying.

2019-02-20 08:59 UTC, plague006 commented on map_gen/Diggy/Feature/Experience.lua
> +    local old_modifier = (force.manual_mining_speed_modifier == 0) and 0 or force.manual_mining_speed_modifier - mining_efficiency.active_modifier
Rather than only accounting for a force.modifier of 0, this should put a floor of 0 on `force.manual_mining_speed_modifier - mining_efficiency.active_modifier` to prevent a situation where a mod sets a number `> 0` but `< active_modifier` (as this would result in a net debuff to players).

2019-02-20 20:52 UTC, SimonFlapse commented on map_gen/Diggy/Feature/Experience.lua
> +    local old_modifier = (force.manual_mining_speed_modifier == 0) and 0 or force.manual_mining_speed_modifier - mining_efficiency.active_modifier
Sounds fair. `force.manual_mining_speed_modifier - mining_efficiency.active_modifier` should never be < 0. I think that's everything we can do/should want to do about this issue.

2019-02-20 20:53 UTC, SimonFlapse commented on map_gen/Diggy/Feature/Experience.lua
> +    Experience.update_health_bonus(force, 0)
Sounds fair. `force.manual_mining_speed_modifier - mining_efficiency.active_modifier` should never be < 0. I think that's everything we can do/should want to do about this issue.

2019-02-20 20:53 UTC, SimonFlapse commented on map_gen/Diggy/Feature/Experience.lua
> +    local old_modifier = (force.manual_mining_speed_modifier == 0) and 0 or force.manual_mining_speed_modifier - mining_efficiency.active_modifier
Sounds fair. `force.manual_mining_speed_modifier - mining_efficiency.active_modifier` should never be < 0. I think that's everything we can do/should want to do about this issue.

2019-02-20 23:13 UTC, SimonFlapse commented on map_gen/Diggy/Feature/Experience.lua
> +    Experience.update_health_bonus(force, 0)
That seems like the wrong way to do it. Diggys buffs simply would not be compatible with the mod then. We can't, and should not put too much effort into making this compatible with mods.

2019-02-21 08:32 UTC, plague006 commented
On phone so evaluating is a bit difficult but:
It seems the incorrect style is being applied in regards to this line of the style guide:
No spaces after (, [, { or before ], ), }.

In addition, I think force.modifier == 0 and 0 is redundant now that you are instituting a floor of 0.

2019-02-21 19:12 UTC, plague006 commented on map_gen/maps/diggy/feature/experience.lua
> +        local old_modifier = (force.manual_mining_speed_modifier == 0) and 0 or force.manual_mining_speed_modifier - mining_efficiency.active_modifier
Pretty sure `(force.manual_mining_speed_modifier == 0) and 0 or ` is redundant since we're covering all cases where `force.manual_mining_speed_modifier < mining_efficiency.active_modifier`

2019-02-21 19:12 UTC, plague006 commented on map_gen/maps/diggy/feature/experience.lua
> +    Experience.update_inventory_slots(force, 0)
As discussed, "fighting" other mods for control every second might make for a worse player experience

2019-02-21 19:54 UTC, SimonFlapse commented on map_gen/maps/diggy/feature/experience.lua
> +    Experience.update_inventory_slots(force, 0)
That should only happen if the mod keeps setting the modifier to 0. And if it does we are not at fault. People must understand that adding mods can cause incompatible and inconsistency. I still don't think there is anything else we can do. So either we go with these changes or we just close the PR and not do anything.

2019-02-21 20:07 UTC, plague006 commented on map_gen/maps/diggy/feature/experience.lua
> +    Experience.update_inventory_slots(force, 0)
I don't think we should add behaviour to combat other mods directly as we don't know if we will make things better or worse, but I think clamping the value of `old_modifier` to not be negative is a very worthwhile change.

2019-02-21 20:12 UTC, SimonFlapse commented on map_gen/maps/diggy/feature/experience.lua
> +    Experience.update_inventory_slots(force, 0)
Agree, that's a good find :) But we'd not have a solution for #673 and it would keep being brought up

2019-02-21 20:56 UTC, plague006 commented on map_gen/maps/diggy/feature/experience.lua
> +    Experience.update_inventory_slots(force, 0)
We can't control what other mods do. All we can do is try to be compatible with others, we can't force them to be compatible with others.

2019-02-21 20:57 UTC, plague006 commented on map_gen/maps/diggy/feature/experience.lua
> +        local old_modifier = (force.manual_mining_speed_modifier == 0) and 0 or force.manual_mining_speed_modifier - mining_efficiency.active_modifier
```suggestion
        local old_modifier = force.manual_mining_speed_modifier - mining_efficiency.active_modifier
```

2019-02-21 20:57 UTC, plague006 commented on map_gen/maps/diggy/feature/experience.lua
> +        local old_modifier = (force.manual_mining_speed_modifier == 0) and 0 or force.manual_mining_speed_modifier - mining_efficiency.active_modifier
The suggestion this is neat

2019-02-21 20:58 UTC, plague006 commented on map_gen/maps/diggy/feature/experience.lua
> +        local old_modifier = (force.character_inventory_slots_bonus == 0) and 0 or force.character_inventory_slots_bonus - inventory_slots.active_modifier
```suggestion
        local old_modifier = force.character_inventory_slots_bonus - inventory_slots.active_modifier
```

2019-02-21 20:58 UTC, plague006 commented on map_gen/maps/diggy/feature/experience.lua
> +        local old_modifier = (force.character_health_bonus == 0) and 0 or force.character_health_bonus - health_bonus.active_modifier
```suggestion
        local old_modifier = force.character_health_bonus - health_bonus.active_modifier
```

2019-02-21 20:58 UTC, plague006 commented on map_gen/maps/diggy/feature/experience.lua
> +    Experience.update_health_bonus(force, 0)
Why is this new? Was there a reason health bonus wasn't handled here?

2019-02-21 21:41 UTC, SimonFlapse commented on map_gen/maps/diggy/feature/experience.lua
> +    Experience.update_health_bonus(force, 0)
It wasn't needed, since no research added extra health. I've added it for consistency, and it ensures that all the buffs are force updated on a new research as well as every 61 ticks

2019-02-21 21:42 UTC, SimonFlapse commented on map_gen/maps/diggy/feature/experience.lua
> +        local old_modifier = (force.character_health_bonus == 0) and 0 or force.character_health_bonus - health_bonus.active_modifier
Yeah that'll work now since we are preventing the ´old_modifier´ from going below 0

2019-02-21 22:02 UTC, mheguy approved these changes

2019-02-21 22:02 UTC, merged