Changed error when no map is selected
Valansch/RedMew pull request #766
Opened 2019-02-17 11:55 UTC by Valansch

![](http://puu.sh/CNxeV/c7560ed069.jpg)

I intentially didnt say how to select a map because that would have made the error message bigger and the bigger the error message the lower the chance that it will be read.

@plague006 I am sorry Father for I have sinned.

2019-02-17 16:51 UTC, mheguy requested changes

2019-02-17 16:51 UTC, plague006 commented on map_gen/shared/map_loader.lua
> +	error('\n NO MAP SELECTED \n The RedMew scenario contains many different maps. If you are unsure how to select a map checkout our guide at: \n https://redmew.com/guide \n -The RedMew Team ', 0)
Please tell them that the error is that they downloaded the repository instead of a release. If you recall, one of the major reasons for not including `map_selection.lua` is so that they download a release which has a version number.

2019-02-17 17:19 UTC, Valansch commented on map_gen/shared/map_loader.lua
> +	error('\n NO MAP SELECTED \n The RedMew scenario contains many different maps. If you are unsure how to select a map checkout our guide at: \n https://redmew.com/guide \n -The RedMew Team ', 0)
But what if they want to tinker with it? How does a release help? We have so many maps this would limit them from only using the ones in our releases.

2019-02-19 02:52 UTC, plague006 commented on map_gen/shared/map_loader.lua
> +local success, shape = pcall(function() require 'map_selection' end)
`return require 'map_selection'`

2019-02-19 02:53 UTC, mheguy submitted a review, later dismissed

2019-02-19 02:53 UTC, plague006 commented on map_gen/shared/map_loader.lua
> +local success, shape = pcall(function() require 'map_selection' end)
return require 'map_selection'

2019-02-19 03:03 UTC, plague006 commented on map_gen/shared/map_loader.lua
> +	error('\n NO MAP SELECTED \n The RedMew scenario contains many different maps. If you are unsure how to select a map checkout our guide at: \n https://redmew.com/guide \n -The RedMew Team ', 0)
Per discussion on discord:
```
\n\n--map_selection.lua not found--\nReleases on github include this file.\nFor info: \nhttps://redmew.com/guide
```

2019-02-19 16:03 UTC, Valansch commented on map_gen/shared/map_loader.lua
> +local success, shape = pcall(function() require 'map_selection' end)
🤦‍♂️

2019-02-19 16:06 UTC, Valansch commented
@plague006 resolved

2019-02-19 16:22 UTC, grilledham commented
As a developer the `pcall` is very annoying as it turns the useful error message into a message about not loading a map.
Can we change map_loader.lua to this:
```lua
local shape = require 'map_selection'
if shape == true then
	error('\n\n--map_selection.lua not found--\nReleases on github include this file.\nFor info: \nhttps://redmew.com/guide\n - The RedMew Team ', 0)
end

local b = require 'map_gen.shared.builders'
local RS = require 'map_gen.shared.redmew_surface'
local config = global.config.map_generation

if #config.entity_modules > 0 then
    shape = shape or b.full_shape
    shape = b.apply_entities(shape, config.entity_modules)
end

if #config.terrain_modules > 0 then
    shape = shape or b.full_shape

    for _, m in ipairs(config.terrain_modules) do
        shape = b.overlay_tile_land(shape, m)
    end
end

if type(shape) == 'function' then
    local surfaces = {
        [RS.get_surface_name()] = shape
    }

    local gen = require('map_gen.shared.generate')
    gen.init({surfaces = surfaces, regen_decoratives = config.regen_decoratives, tiles_per_tick = config.tiles_per_tick})
    gen.register()
end
```
And map_gen.maps.default.lua to:
```lua
-- A blank file to allow map_selection to have a default
return false
```
Or am I missing something?

2019-02-19 18:56 UTC, plague006 commented
Val's initial comment/proposal was off the mark in my opinion. This PR/issue is not about selecting a map. We have the default map because we explicitly don't require them to select a map. 

The issue this PR seeks to resolve is for the following use-case: an end user unfamiliar with LUA and coding in general downloads the repository instead of a release. They have no `map_selection.lua` and they run the scenario. They are greeted with a big unfriendly error message which means nothing to them.

This PR basically just changes the error from this:
![image](https://user-images.githubusercontent.com/10162554/53039744-d314e980-344d-11e9-9dd6-38e259acf7f2.png)

to this:
![image](https://user-images.githubusercontent.com/10162554/53039782-f049b800-344d-11e9-986c-5b9d8fa1d25e.png)

On a related note, we could also expand the error message we give for no map required. That case is handled in the penultimate line of code in the file: `error('You forgot to require a map')`

2019-02-20 10:56 UTC, grilledham commented
To be clear my issue with this current implementation is the suppressing of errors to devs.

Suppose I make this simple syntax error, or any other error for that matter.
![image](https://user-images.githubusercontent.com/10003572/53086684-7a9d2500-34fd-11e9-9a50-55c80f6a253d.png)

Before we would get an error message telling us where the mistake was.
![image](https://user-images.githubusercontent.com/10003572/53086591-4de90d80-34fd-11e9-8a06-7bb0bc852f5c.png)

Now we get a useless and misleading message. 
![image](https://user-images.githubusercontent.com/10003572/53086541-390c7a00-34fd-11e9-8ab4-f4c3ee089485.png)
This would be particularly confusing for a dev who wasn't in the loop about this change.

I think my proposal above gives, us what we want. But really I'd be happy with any proposal that doesn't suppress the error message when a map is loaded correctly, but there is an error in it.

2019-02-20 11:01 UTC, linaori commented
We should check what error it is with pcall and give the proper message (like how exceptions work)

2019-02-20 15:21 UTC, plague006 commented
You're right about errors in the map functions. I completely failed to consider that.

```if shape == true then error```
`require` returns `true` if a map has a nil return, so we would have to make sure all maps that do not return a function explicitly return `false`

2019-02-20 16:09 UTC, grilledham commented
> `if shape == true then error`
`require` returns `true` if a map has a nil return, so we would have to make sure all maps that do not return a function explicitly return `false`

I agree that is annoying, we need a better solution.

2019-02-21 19:58 UTC, plague006 commented
If the file `map_selection.lua` exists then require will return the map's value or true if nil.
So we could force all maps to not return nil and we check for that.
pcall can give a friendly warning to end users downloading the repository but will suppress map errors.

I think in this case the greatest benefit with the lowest harm is to do nothing but include a note at the top of the readme so that users ending up in our repo have the best chance of seeing it. If I'm being realistic though, end users *will not* download the repository, nor will they download source code from releases.

Eventually we will figure out deflating dynamic requires and that will give us more options.

2019-02-24 00:11 UTC, plague006 commented
Closing after speaking with Val on discord: no good way to fix this atm.

2019-02-24 00:11 UTC, closed without merging