Added logic for toggling minable robots
Valansch/RedMew pull request #790
Opened 2019-02-22 11:59 UTC by SimonFlapse

I couldn't find anything in the upcoming feature section of the wiki that robots shouldn't be minable in 0.17

This adds a check everything a player selects a construction robot that:
- Checks is the construction robot is owned by a specific player
  - If not: Sets the construction robot to minable = false
  - If: Sets the construction robot to minable = true

This will practically prevent other players from intentional, or unintentional, mine a players personal construction robots.

You might be able to mine a robot if you select it first and the owner selects it afterwards, and you do not remove your selection. I think this is an edge case that's not worth trying to fix.

2019-02-22 12:04 UTC, Valansch submitted a review, later dismissed
Great idea!
One minor thing.

2019-02-22 12:04 UTC, Valansch commented on features/save_bots.lua
> +    local player = Game.get_player_by_index(event.player_index)
Move this line to line 19 please. Preserve_bot will be called alot.

2019-02-22 12:07 UTC, SimonFlapse commented on features/save_bots.lua
> +    local player = Game.get_player_by_index(event.player_index)
Yeah I know, but I can't :( The event only passes on the previous selected item, not the new one. So I need the player

2019-02-22 12:08 UTC, Valansch commented on features/save_bots.lua
> +    local player = Game.get_player_by_index(event.player_index)
Oh i missed line 6.

2019-02-22 12:13 UTC, grilledham commented on features/save_bots.lua
> +        local logistic_cell = entity.logistic_network.cells[1]
Can you use <https://lua-api.factorio.com/latest/LuaEntity.html#LuaEntity.logistic_cell> instead?
Also do we need to check if cell is nil, what happens if you select a robot and there are no logistic_cell on the map?

2019-02-22 12:19 UTC, SimonFlapse commented on features/save_bots.lua
> +        local logistic_cell = entity.logistic_network.cells[1]
I tried initially but didn't seem to work very well. And the player will always only have one cell. My local changes have a check for a nil cell

2019-02-22 12:21 UTC, SimonFlapse commented on features/save_bots.lua
> +        local logistic_cell = entity.logistic_network.cells[1]
![image](https://user-images.githubusercontent.com/44922798/53242359-c6d69980-36a4-11e9-8282-27aa932727a7.png)

2019-02-22 20:12 UTC, plague006 commented
Because of the small size and scope, this would be a good fit for `redmew_qol`.

2019-02-22 22:57 UTC, SimonFlapse commented
Is it a problem to have it isolated? I could understand if you wanted to reuse the same event to reduce overhead.

2019-02-23 15:37 UTC, plague006 commented
Not a problem to have it isolated, nope. Was just a suggestion since it's a good fit.

2019-03-03 22:46 UTC, SimonFlapse commented
Updated to 0.17 and moved to Redmew-QoL.lua

2019-03-04 06:33 UTC, mheguy requested changes
You have two copies of the module in this PR.

2019-03-04 06:34 UTC, plague006 commented on features/redmew_qol.lua
> +    if entity == nil or not entity.valid then
As a style choice, I'm wondering why you use `== nil` and `not` both?

2019-03-04 10:30 UTC, mheguy approved these changes

2019-03-04 12:02 UTC, merged