First shot at #608 Corpse Cleanup
Valansch/RedMew pull request #943
Opened 2019-06-04 19:30 UTC by Starholme

This is a revival and partial re-write of #883 that was abandoned.

It looks at corpses within a small range of any new corpse, and randomly removes to get under the limit. Although it has to run every time an entity dies, it only touches a small area (36 tiles), so it should be fairly low impact. The number of corpses and radius are adjustable, but these values seem reasonable. The 'after' screenshot is using these settings.

I've tested what I can think of, but I'm open to suggestions.

![After](https://user-images.githubusercontent.com/1916332/58908045-c77fc280-86cc-11e9-8234-2da0b08ec140.PNG)
![Before](https://user-images.githubusercontent.com/1916332/58908046-c8185900-86cc-11e9-816c-024995ed6220.PNG)

2019-06-04 20:02 UTC, linaori requested changes
I like the idea of it being random, but this is going to be a really heavy script. What if instead of doing this every biter death, the position is marked for cleanup at a later point? It would roughly translate to this:

1) a biter dies & entity.valid
2) 5% chance of garbage collection
3) is the location (+ range) already marked for cleanup, stop
4) set down marker for this position (+ range)
5) register event to clean location in X ticks (say 9000 ticks)
6) do the cleanup as you have here (random is fine I guess)

Another option is to keep trick of all actual positions of entities that died and at what tick, then you can calculate back which entities should be removed on those positions

2019-06-04 20:02 UTC, linaori commented on features/biter_corpse_util.lua
> +    if entity.valid then
Can you turn those into guard clauses to reduce nesting?
```lua
if not entity.valid then
    return
end
```
```

2019-06-04 20:02 UTC, linaori commented on features/biter_corpse_util.lua
> +        if surface.count_entities_filtered {
Same in regards of the guard clause

2019-06-04 20:06 UTC, grilledham reviewed
Thanks for the PR.

I've suggested one bug fix and 2 micro optimisations. 

Thinking about it further would it make more sense to only listen for `dying_force.name == 'biter'` rather than not `'player'`? If for example trees being grenaded counts as neutral force dying.

Also what happens when non biter entities on the enemy force die, like say when outpost turrets are destroyed in crashsite. Do we want that triggering the corpse removal logic?

Performance wise, it's hard to predict what can cause bad performance without trying it. So I'm willing to try this and see what happens.

2019-06-04 20:06 UTC, grilledham commented on features/biter_corpse_util.lua
> +        if dying_force == 'player' then
I don't think this works unless you do `dying_force.name == 'player'

2019-06-04 20:06 UTC, grilledham commented on features/biter_corpse_util.lua
> +        if surface.count_entities_filtered {
The table that is passed to `count_entities_filtered ` is the same as the table that is passed to `find_entities_filtered ` can we make a `local filter = {...}` and reuse it?

2019-06-04 20:06 UTC, grilledham commented on features/biter_corpse_util.lua
> +            local num_to_remove = #corpse_list - biter_utils_conf.corpse_threshold
Just because this code might potentially run quite a lot can I request the micro optimisation of making a `local count = #corpse_list`?

2019-06-04 20:10 UTC, Starholme commented on features/biter_corpse_util.lua
> +        if dying_force == 'player' then
Is there a list of these values somewhere? I'm sure there has to be, I just can't find anything...

2019-06-04 20:14 UTC, Starholme commented on features/biter_corpse_util.lua
> +        if surface.count_entities_filtered {
I tried it like this and it didn't work. Just found every entity:
```
local filter={
                position = entity.position,
                radius = biter_utils_conf.radius,
                type = 'corpse',
                force = 'neutral'
                }
surface.count_entities_filtered {filter}
```
Seems like it should be possible though. Any suggestions?

2019-06-04 20:17 UTC, grilledham commented on features/biter_corpse_util.lua
> +        if dying_force == 'player' then
<https://lua-api.factorio.com/latest/LuaForce.html>

<https://lua-api.factorio.com/latest/LuaForce.html#LuaForce.name> for the name property

<https://lua-api.factorio.com/latest/> for the whole modding api

2019-06-04 20:20 UTC, grilledham commented on features/biter_corpse_util.lua
> +        if surface.count_entities_filtered {
I was suggesting this
```lua
local filter = {
    position = entity.position,
    radius = biter_utils_conf.radius,
    type = 'corpse',
    force = 'neutral'
}
if surface.count_entities_filtered(filter) > biter_utils_conf.corpse_threshold then
    -- Get the actual entities
    local corpse_list = surface.find_entities_filtered(filter)

    -- rest of code
end
```
Which I think should work

2019-06-04 20:45 UTC, Starholme commented on features/biter_corpse_util.lua
> +        if dying_force == 'player' then
Done, now checks that they are part of the default 'enemy' force.

2019-06-04 20:50 UTC, Starholme commented on features/biter_corpse_util.lua
> +        if surface.count_entities_filtered {
Thanks, I knew it should be possible, but I'm pretty new to lua. Mostly a c# guy.
Should be resolved in the latest commit.

2019-06-04 20:57 UTC, Starholme commented
> I like the idea of it being random, but this is going to be a really heavy script. What if instead of doing this every biter death, the position is marked for cleanup at a later point? It would roughly translate to this:
> 
> 1. a biter dies & entity.valid
> 2. 5% chance of garbage collection
> 3. is the location (+ range) already marked for cleanup, stop
> 4. set down marker for this position (+ range)
> 5. register event to clean location in X ticks (say 9000 ticks)
> 6. do the cleanup as you have here (random is fine I guess)
> 
> Another option is to keep trick of all actual positions of entities that died and at what tick, then you can calculate back which entities should be removed on those positions

I'm concerned that we will end up with one 'big' slowdown every 9000 ticks, instead of a 'small' slowdown on each death. I could implement point 2 though, just ignore x% of the calls. Would avoid the overhead of counting entities each time.
I don't think we can actually find out which would work better without building and testing both.

2019-06-04 21:22 UTC, grilledham approved these changes
While I think linaori suggestion could be more performant, I'm willing to give this a try and see what happens.

2019-06-04 21:22 UTC, grilledham commented on features/biter_corpse_util.lua
> +    if not (surface.count_entities_filtered(filter)  > biter_utils_conf.corpse_threshold) then
Rather than `not` you could invert `>` to `<=`.
I personally find it reads better that way.

2019-06-04 21:26 UTC, Starholme commented on features/biter_corpse_util.lua
> +    if not (surface.count_entities_filtered(filter)  > biter_utils_conf.corpse_threshold) then
Good point. Done.

2019-06-06 07:37 UTC, linaori commented
The thing I'm most worried of, is that we will do 2 surface lookups for a big portion of death events. Diggy stress map proves that it's not a performance issue to store a massive table of coordinates and in this scenario we'd only store 0~20 max or so. Every X ticks 2 surface lookups with a random to kill corpses is far more performant than doing this every few deaths.

2019-06-09 03:42 UTC, mheguy approved these changes
Reviewing since I was requested:
I'm too out of the loop to have an informed opinion on what the current scenario can and can't handle performance-wise.
With that said, I like seeing initiative and someone willing to write code. I think this definitely deserves a shot and can be modified if needed.

2019-06-10 04:41 UTC, Starholme commented
Ok, complete rewrite. It's using the basic structure suggested by @linaori above.

Store each corpse, from the post_entity_died event, into a table grouped by the position.
If a position has more than the threshold, remove some.
Once and a while, trim the table by removing any old corpses and empty positions.
Does zero surface api calls.

If you are trying it out, it's most obvious to see the behavior if you either increase the chunk size or reduce the corpse threshold. At the current settings you really need to be looking to see that it's removing much.

2019-06-10 11:03 UTC, grilledham commented
This works a bit differently to how I'd imagined it.

 `entity.position.x % biter_utils_conf.chunk_size`
Calculating the hash position using a module strikes me as odd. Wouldn't that mean every n tiles counts as being in the same chunk? What about:
`math.floor(entity.position.x / biter_utils_conf.chunk_size)`

I'm not sure if the `remove_outdated_corpses()` function is worth it. I think the `corpse_cleanup()` function is sufficient to do the clean up. What are your thoughts on this?

I haven't tested this yet, can you recommend a good way to test it?

2019-06-10 18:34 UTC, Starholme commented
> This works a bit differently to how I imagined it.
> 
> `entity.position.x % biter_utils_conf.chunk_size`
> Calculating the hash position using a module strikes me as odd. Wouldn't that mean every n tiles counts as being in the same chunk? What about:
> `math.floor(entity.position.x / biter_utils_conf.chunk_size)`
> 
> I'm not sure if the `remove_outdated_corpses()` function is worth it. I think the `corpse_cleanup()` function is sufficient to do the clean up. What are your thoughts on this?
> 
> I haven't tested this yet, can you recommend a good way to test it?

With the full line being entity.position.x - (entity.position.x % biter_utils_conf.chunk_size), it makes sense.
Example: x = 47, so 47 - (47 % 3) = 47 - 2 = 45
Essentially gives you the same result as the math.floor you mention.

corpse_cleanup is responsible for removing excessive corpses from the map.
remove_outdated_corpses is all about pruning the stored list, so we don't hang onto extra entities or chunks when they no longer make sense (ie: factorio has removed the corpse because it is more than 15 minutes old)

Testing for me was like this:
- Start new scenario, set player to god, research all techs, set always day
- Find a biter nest, plop down a few turrets full of ammo
- Crank up the game speed
- See how things go
To test the remove_outdated_corpses, you'll need to remove the first set of turrets, go find a nest somewhere else and set them up. Probably want to add a print statement when it removes an empty corpse_chunk on line 46. If you print the key, it will be the x and y.

2019-06-11 16:06 UTC, grilledham commented
> With the full line being entity.position.x - (entity.position.x % biter_utils_conf.chunk_size), it makes sense.

Right you are, my mistake.

As a suggestion, what about we only keep the corpse count for each chunk. Then once it exceeds a limit we get all the corpses for the chunk, remove half and update the count.

That way we don't need to clear out expired corpses. Plus storing data in global increases save / load time.

Thoughts?

2019-06-11 16:09 UTC, grilledham commented
For the diggy map we had to store lots of data by position / chunk.
So we tested 3 different ways to do that:
 - string hash (what you are doing)
 - number hash
 - table of tables

Turns out table of tables is the fastest.

2019-06-11 18:08 UTC, Starholme commented
@grilledham I think the big difference here is that we only ever expect to see a few dozen 'chunks', each with less than 20 corpses. The amount of data is never very large, with a worst case being something like 100 chunks * 20 corpses = 2000 total iterations.

The tradeoff comes down to mine requiring more looping vs yours requiring more surface api calls (because you only have the count, you have to check the map)

It's a little difficult to benchmark some of these things, hard to get a concrete answer.

2019-06-13 14:12 UTC, Starholme commented
On discord, @linaori mentioned that this can be merged

2019-06-13 15:49 UTC, grilledham commented
@Starholme 

There are a few micro optimisations that I see no harm in adding, like making some local variables where values are used more than once. Also I would like to turn the string hash into a table of tables.

Would you like me to commit the changes directly into this PR, or would you prefer I outline the changes and you make them?

2019-06-13 16:18 UTC, Starholme commented
@grilledham Go ahead and make the changes

2019-06-13 21:34 UTC, grilledham commented
I ended up playing around with this quite a bit.
Changes I made:
- Covert hash to table of tables
- Used locals for repeated values.
- Noticed that `corpse_cleanup` would only ever clean up one corpse per call, so I inlined the logic.
- Changed the old corpse cleanup logic to be based on biters killed rather than if a biter was killed in the right tick. This removes a problem where if lots of biters are killed on the right tick (say a grenade) the cleanup logic would be called multiple times in the same tick.
- Changed the corpse_threshold from 10 to 3. This is just my personal opinion, if someone wants to change the config value they can.
- Renamed the module to `biter_corpse_remover`

I think a good way to test this is to put the following in map_selection.lua
```lua
_DEBUG = true
_CHEATS = true

local b = require 'map_gen.shared.builders'

local spawners = b.throttle_world_xy(b.full_shape, 1, 8, 1, 8)
spawners = b.subtract(spawners, b.circle(32))
spawners = b.entity(spawners, 'biter-spawner')

map = b.apply_entity(b.full_shape, spawners)

return map
```

2019-06-14 16:25 UTC, linaori approved these changes

2019-06-14 17:56 UTC, merged