Added rail_grid map preset and preview
Valansch/RedMew pull request #980
Opened 2019-09-11 18:34 UTC by Jayefuu

A map preset with grass rail grid to enforce rail blocks. Played and tested with modded but also suitable for vanilla.

2019-09-11 18:39 UTC, grilledham commented on map_gen/maps/rail_grid.lua
> +    map = b.change_map_gen_tile(map, old_tile, new_tile)
I want to add a function to builders that would make this easier/ more efficient.

2019-09-11 18:41 UTC, Jayefuu commented on map_gen/maps/rail_grid.lua
> +    map = b.change_map_gen_tile(map, old_tile, new_tile)
I'm not sure why Soggs changed it to this. Previously I added a function to RS map_gen_settings that allowed everything but grass. Something to do with the RSO starting areas we needed for the modded run maybe meant we had to change to changing map gen tiles instead?

2019-09-11 18:59 UTC, theorangeangle commented
Do you have ideas for a description (and bullet-point info)?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

2019-09-11 19:22 UTC, Jayefuu commented
> 
> 
> Do you have ideas for a description (and bullet-point info)?
> 
> Sent with [GitHawk](http://githawk.com)

See line 27? I added a map description already.

2019-09-11 19:32 UTC, theorangeangle commented
Ok, will copy/paste them onto the wiki now :D 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

2019-09-11 19:53 UTC, grilledham commented on map_gen/maps/rail_grid.lua
> +RS.set_spawn_position({x = 20,y = 20})
Is there a reason this is needed over say translating the map?
The advantage of translating the map is it will work even if another script disables the redmew surface.

2019-09-11 20:01 UTC, Jayefuu commented on map_gen/maps/rail_grid.lua
> +RS.set_spawn_position({x = 20,y = 20})
No, personally I always do map = b.translate(map,20,20). Soggs added the spawn position change though. I suppose one advantage is its clear from the function name why the line was added.

2019-09-11 20:08 UTC, grilledham commented on map_gen/maps/rail_grid.lua
> +			ghost_name = entity.ghost_name
`ghost_name` is a global, you don't want to be doing that.
I suggest changing the line to `name = entity.ghost_name`
Then the logic below becomes simpler.
```lua
if (name ~= 'straight-rail') and (name ~= 'curved-rail') then
			if not ghost then
			    return
			elseif (ghost_name ~= 'straight-rail') and (ghost_name ~= 'curved-rail') then
				return
			end
        end
```
to
```lua
if (name ~= 'straight-rail') and (name ~= 'curved-rail') then
    return
end
```

2019-09-11 20:08 UTC, grilledham commented on map_gen/maps/rail_grid.lua
> +               return
I think if you are going to do this check it would make sense to do it before you access `p.surface` above.

2019-09-11 20:09 UTC, grilledham commented on map_gen/maps/rail_grid.lua
> +        --check for sand under all tiles in bounding box
Comment is wrong, should say it's checking for a tile that is not landfill.

2019-09-11 20:10 UTC, grilledham commented on map_gen/maps/rail_grid.lua
> +    map = b.change_map_gen_tile(map, old_tile, new_tile)
Yeah I think it had something to do with RSO, but you would have to ask Soggs for the details.

2019-09-11 20:13 UTC, grilledham requested changes
I think this is mostly good. A few small changes to the prevent rail logic.

Also we will have to fix the travis linting issues. Ask if you need help with that.

Then this should be good to go.

2019-09-18 06:42 UTC, Jayefuu commented
Thanks, those all make sense. I will try get to them soon.

2019-09-28 13:26 UTC, grilledham commented
I refactored this. 
I made a rail_grid directory and separated the parts into different files, this should make reuse of the code easier.

2019-09-28 13:41 UTC, grilledham approved these changes

2019-10-05 10:45 UTC, merged